### ISSUE TITLE
XCP-ng Center 7.6

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#101]
@stormi for your tracking :-)

Note to myself:
* [X] import "release/lima/master" from upstream, push to repo as "upstream-7.6"
* [x] setup job on buildserver

**Comment by stormi** [comment]
Thanks, I was going to ask soon :)

**Comment by borzel** [comment]
I had a feeling ;-)

**Comment by borzel** [comment]
@stormi here is the first package: https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.0-RC1

**Comment by borzel** [comment]
XCP-ng Center 7.6.0 RC3 - https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.0-RC3

**Comment by borzel** [comment]
Just waiting for tests. If all is ok, RC3 becomes the 7.6.0 release

**Comment by borzel** [comment]
Release is released: https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.0
