### ISSUE TITLE
Unable to add shared storage to cluster using XCP-ng Center 7.6

### ISSUE THREAD

**Issue by justlikeef** [xcp-ng/xenadmin#105]
**Describe the bug**
When you click on the button to Scan Target after specifying the portal IP address in the iSCSI configuration dialog, you get an error message '{"error":"Missing portal address"}'

**Comment by borzel** [comment]
@justlikeef Can you please give more details?

I tried with XCP-ng 7.5, XCP-ng Center from 7.6 branch and FreeNAS 11.2:

![grafik](https://user-images.githubusercontent.com/5782951/46756436-bf9b8a00-ccc7-11e8-8dde-ec916fd2ac72.png)

**Comment by justlikeef** [comment]
The screenshot you provided will mount the Lun on the house with that iqn,
but not on any of the other hosts because their iqn is different. When you
drop down the iqn list, there should be an * entry which in xen center
mounts it on each hot using that host's in.

**Comment by borzel** [comment]
hmm.. no problem:

![grafik](https://user-images.githubusercontent.com/5782951/46882375-ba1c7c00-ce4e-11e8-8677-d59e16fec8a3.png)

![grafik](https://user-images.githubusercontent.com/5782951/46882403-d9b3a480-ce4e-11e8-8c18-18fe8cb202d9.png)

**Comment by borzel** [comment]
@justlikeef please reopen if you have new feedback for us
