### ISSUE TITLE
installed in "Program Files (x86)" but the executable is 64 bit

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#113]
**Describe the bug**
7.6.0 RC3 installed in "Program Files (x86)" but the executable is 64 bit, shouldn't it be installed in "Program Files" instead?

**To Reproduce**
1. Go to https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.0-RC3
2. download and install https://github.com/xcp-ng/xenadmin/releases/download/v7.6.0-RC3/XCP-ng-Center-7.6.0.6-RC3.msi

**Expected behavior**
Installed to "Program Files"

**Screenshots / Logfiles**
n/a

**Hard-/Software involved:**
 - Hardware: Intel i7 3770K, 16GB
 - Host XCP-ng Version: 7.5.0-2
 - Client XCP-ng Center Version: 7.6.0-RC3
 - Desktop OS: Windows 10 1803 x64

**Additional context**
n/a

Update:
Citrix seems to do it the same way.

**Comment by borzel** [comment]
That's maybe because our installer doesn't check for bitnes :-/

**Comment by borzel** [comment]
I did a test with the installer and used `ProgramFiles64Folder`, but it refuses to use it, instead a new installation is put in "program files (x86)" :-(

![grafik](https://user-images.githubusercontent.com/5782951/52303732-0a38c480-2991-11e9-88bd-bbf53650d5c5.png)

Does anyone hava an idea?

**Comment by schulz-alexander** [comment]
we will not work on that
