### ISSUE TITLE
Remove or disable GFS2 Clustering in XCP-ng 7.5

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#115]
**Describe the bug**
GFS2 is not supported with XCP-NG and should be grayed out or removed for XCP-NG-Servers / Pools.
(there may be more context menus regarding these features, have not checked)

Upgrading from XCP-NG 7.5 to 7.6 with Clustering enabled will cause troubles: 
https://github.com/xcp-ng/xcp/issues/94

**To Reproduce**
1. Go to pool properties
2. Click on Clustering

**Expected behavior**
Grayed out with a hint that this is not supported.

**Screenshots / Logfiles**

![pool-clustering](https://user-images.githubusercontent.com/1071741/48064702-e2d32f80-e1c8-11e8-887b-3764cd46980e.png)

**Hard-/Software involved:**
 - Hardware: VMware virtual machine for testing
 - Host XCP-ng Version: 7.5
 - Client XCP-ng Center Version: 7.6.0.9
 - Desktop OS: Windows 10 1803

**Additional context**

**Comment by borzel** [comment]
It should already be removed: https://github.com/xcp-ng/xenadmin/issues/108

**Comment by cocoon** [comment]
I think I had a version of 7.5 that reports gfs2 support then, ... I will have to check this.

But I can say XCP-NG Center 7.6.0.9 shows that Option If I restore my 7.5 Backup. 

That means it would only affect you if you install 7.5.

**Comment by borzel** [comment]
so it's a job for @johnelse or @stormi or @olivierlambert ... I close this issue :-)

**Comment by olivierlambert** [comment]
LGTM

**Comment by stormi** [comment]
Follow-up: https://github.com/xcp-ng/xcp/issues/94
