### ISSUE TITLE
Can't create new iSCSI (LVM) SR - get error about GFS2 driver 

### ISSUE THREAD

**Issue by sammcj** [xcp-ng/xenadmin#116]
Copied from https://github.com/xcp-ng/xcp/issues/95

When creating a iSCSI (LVM) SR you get an error about GFS2

To reproduce:

- Perform fresh install of XCP-NG 7.6, selecting default options when prompted.
- Connect to newly installed host in XCP-NG centre
- Attach SR, select iSCSI
- Note than thinly provisioned LVMoiSCSI doesn't seem to be an option (offers GFS2 but is greyed out due to licensing)
- Select the only option (Full provisioned LVM)
- Enter Target, Scan for and select IQN and LUN
- Click next and get error that the GFS2 driver is not found

**Expected behavior**

The iSCSI LUN should be attached and a SR created.

**Screenshots / Logfiles**

![](https://user-images.githubusercontent.com/862951/47974951-e353c380-e0ff-11e8-80ec-5ade31da63fa.jpg)

Note: The error in this screenshot is only shown after the below GFS2 error occurs and you dismiss the dialogue.
![](https://user-images.githubusercontent.com/862951/47975034-4d6c6880-e100-11e8-9f8e-e65651f13d8d.jpg)

![](https://user-images.githubusercontent.com/862951/47974944-df27a600-e0ff-11e8-9c85-4a11626bd52c.jpg)

**Hard-/Software involved:**
 - Hardware: [e.g. Dell M620]
 - Host XCP-ng Version: [e.g. 7.4.1]
 - Client XCP-ng Center Version: [e.g. 7.4.2-RC2]
 - Desktop OS: [e.g. Windows 10 1803]

**Additional context**

**Comment by olivierlambert** [comment]
Ca you check that "Clustering" option is disabled?

**Comment by sammcj** [comment]
Where is that option?

--
Sam McLeod

**Comment by olivierlambert** [comment]
I'm not using XenCenter/XCP-ng Center, but IIRC recent bug reports, there is an option somewhere for the pool that's called "Clustering".

**Comment by olivierlambert** [comment]
Here:

![](https://user-images.githubusercontent.com/1071741/48062939-d13b5900-e1c3-11e8-9bdb-a0b5bb2b3ab3.png)

**Comment by sammcj** [comment]
Thanks for the link, I’ll do a fresh install tomorrow (21:30 here down under!) and report back. Thanks again.

**Comment by borzel** [comment]
confirmed!

**Comment by borzel** [comment]
@sammcj please test with this corrected version and report back: 
[XCP-ng-Center-7.6.0.13.msi.zip](https://github.com/xcp-ng/xenadmin/files/2563390/XCP-ng-Center-7.6.0.13.msi.zip)

**Comment by sammcj** [comment]
Confirmed fixed, thanks @borzel!

**Comment by rizaemet** [comment]
I'm also experience this problem when adding san storage what fc connected by hba. But after install 7.6.0.13 problem is gone. There is a topic about this issue: https://discussions.citrix.com/topic/398832-error-upon-attaching-new-lun-to-sr/ 
if still they not patch or fix this issue you are faster than them @borzel

**Comment by ahmadsp** [comment]
Just had the same problem, thanks a bunch!
