### ISSUE TITLE
Enhancement: Suspend to RAM (cli: vm pause)

### ISSUE THREAD

**Issue by lurendrejer** [xcp-ng/xenadmin#121]
Xen has the ability to Pause a VM (Suspend to RAM). Which is instant.
The XCP-Center gui only has the Suspend to disk feature - which takes a long time.

Could a Pause/Unpause button be added to the gui? 
Maybe even the ability to pause an entire hosts vm's

More info: https://discussions.citrix.com/topic/329558-what-the-difference-between-cli-vm-suspend-and-vm-pause/

Picture of paused VM's:
![image](https://user-images.githubusercontent.com/30922656/48920308-834b7400-ee98-11e8-88fa-ce9b7cbbae18.png)

**Comment by lurendrejer** [comment]
With this functionality i could pause all my hundreds of vm's within seconds, when the students leave..
Suspending to disk involves writing their three terrabytes of ram to disks.... :-/

**Comment by olivierlambert** [comment]
What's the use case? Free resources while people are AFK on their VMs?

**Comment by lurendrejer** [comment]
Save power and money from 15:15 to 08:00.

I'm already doing so via script, but a busy few would like to work late - and having a gui button would enable them to. :)

**Comment by lurendrejer** [comment]
Pfsense uses 10% of a single core when idling. When running 100-200 doing nothing at all, during the weekend, it gets kinda stupid in cooling, power, etc.

**Comment by borzel** [comment]
I did some tests with `xe vm-pause` and `xe vm-unpause` .. there is some value in having these commands on the gui.

If someone feels free to implement this stuff, I'm the last who won't merge it ;-)

**Comment by lurendrejer** [comment]
We have quite a few developers with very limited experience (currently under education in software development). I'll see if I can do something.

**Comment by olivierlambert** [comment]
@lurendrejer tomorrow or Friday we'll release the feature in Xen Orchestra stable. This will support bulk pause/unpause too (in the home view, you'll be able to filter on VMs, select them and do the pause/unpause at once).

**Comment by lurendrejer** [comment]
Aah neato.
I started our project on xoa, self service was perfect except for some glaring issuesz mostly regarding filtering resources. It uses uuids on creation of resource pools instead of names on usage of the pools. Having the ability to enter "local storage*" is one of the features we are looking to develop in-house. Shared storage is way out of our reach right now, and using uuids instead of names/filters makes every addition of hardware a chore. :)

**Comment by olivierlambert** [comment]
You can't rely on name_label to build anything ;) (because a label is not fixed by definition). But feel free to explain your use case (not a technical solution, but your real use case/the thing you want to achieve in the end) on XO bug tracker. Then we could think on how to do so.

**Comment by lurendrejer** [comment]
I understand - security and stability is key.
Except for us.... :)

We need things to be dynamic.

**Comment by lurendrejer** [comment]
Dynamic resources in self service - that is what we need, actually.

**Comment by olivierlambert** [comment]
Please open (or update if the issue exists) a ticket in XO repo

**Comment by olivierlambert** [comment]
FWI, pause/unpause (individually or in bulk) is here since last Thursday :) ([see this blog post](https://xen-orchestra.com/blog/xen-orchestra-5-29/))

**Comment by lurendrejer** [comment]
I've been testing it from the minute it released, great work 👍

**Comment by cocoon** [comment]
I am still thinking about the two possibilities:

- integrate directly into the UI
- add it as plugin

But I tried directly in the UI and it seems possible ... now I need to add unpause ...

![001-test](https://user-images.githubusercontent.com/1071741/49807909-89c46180-fd5b-11e8-99fc-61b9c98b9726.png)
![002-test](https://user-images.githubusercontent.com/1071741/49807910-8a5cf800-fd5b-11e8-93e1-7d9fff537370.png)

![003-test](https://user-images.githubusercontent.com/1071741/49808051-dd36af80-fd5b-11e8-8f55-4d71d71dada3.png)

**Comment by lurendrejer** [comment]
You are awesome!

**Comment by cocoon** [comment]
Waz back is working, too.
Messages are a placeholder, just to see where that messages appears.

![004-test](https://user-images.githubusercontent.com/1071741/49811659-00655d00-fd64-11e8-899c-431c9f2d74f3.png)
![005-test](https://user-images.githubusercontent.com/1071741/49811661-00655d00-fd64-11e8-83a4-675d5bfe3e08.png)
![006-test](https://user-images.githubusercontent.com/1071741/49811663-00fdf380-fd64-11e8-90bf-086ccad084d8.png)

**Comment by lurendrejer** [comment]
Personally i think that a confirmation dialog for an instant action is a bit overkill.
But if it follows some guideline of the GUI - fine by me :)

Pause could have a dialog, unpause - is a bit much to have the user confirm.

**Comment by borzel** [comment]
@cocoon cool!

**Comment by cocoon** [comment]
oops strange, give me some minutes ...

**Comment by cocoon** [comment]
https://file.io/YvKQnM

**Comment by lurendrejer** [comment]
Hi, been quite busy - I'll be testing it tomorrow morning. 
And, thank you !!

**Comment by lurendrejer** [comment]
Everything seems to be working as planned!
Tested with single and multiple servers.

Thank you!

**Comment by lurendrejer** [comment]
I don't know about the pause and suspend labels - it isn't intuitive to new users.
Shouldn't they be called hibernate and suspend? Maybe suspend to RAM and suspend to disk?

**Comment by lurendrejer** [comment]
Maybe 'Suspend' should be called Save state.
And Pause should be called Suspend/Resume.

That would be instantly recognisable for new users.

**Comment by cocoon** [comment]
I think renaming an command would not be good, because it should match the api / cli command naming.
If somebody is searching for documentation about it, it is much easier if it matches.

But there could be a short info/tooltip or so telling like "(to RAM)" and "(to Disk)".

**Comment by lurendrejer** [comment]
You a completely right :)
But, Force shutdown is called "Hard poweroff" in the API, as far as i know.
So, some form of usability-enhanced naming is already in effect.

**Comment by lurendrejer** [comment]
vmware and hyper-v more or less agreed on suspend/resume and save state in their gui's.

**Comment by borzel** [comment]
It's availabe in our pre-release: https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.3-Preview1

@cocoon I also added two new images for the pause state, so the VM icon has not the same pause symbol like in the suspend state

Suspended
![grafik](https://user-images.githubusercontent.com/5782951/51443208-ad2ce580-1ce5-11e9-8a03-fc4bb62fe068.png)

Paused
![grafik](https://user-images.githubusercontent.com/5782951/51443196-7ce54700-1ce5-11e9-939e-da0318b87e6f.png)
