### ISSUE TITLE
XCP-ng Center flagged for Razy virus

### ISSUE THREAD

**Issue by rwarford** [xcp-ng/xenadmin#122]
**Describe the bug**
XCP-ng Center has been quarantined by my AV software for the **Razy virus**. Is this is a false alarm?

I originally installed from the MSI I downloaded on 10/3/2018. I downloaded and re-installed today (12/3/2018) using the MSI installer (*XCP_ng_Center_Installer.msi*) from *https://github.com/xcp-ng/xenadmin/releases/download/v7.4.1-MSI/XCP_ng_Center_Installer.msi*. XCP-ng center was immediately flagged again.

**My software:**

  * VIPRE Antivirus 2016
  * Windows 7 Home Premium, SP1

**To Reproduce**
1. Download MSI from https://github.com/xcp-ng/xenadmin/releases/download/v7.4.1-MSI/XCP_ng_Center_Installer.msi.
2. Run installer.
3. Scan with VIPRE Antivirus 2016
4. Observer that XCP-ng center has been quarantined for Razy virus.

**Expected behavior**
XCP-ng Center should not be flagged.

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.

**XCP-ng Center:**
 - XCP-ng Center Version: 7.4.1
 - Desktop OS: Windows 7 Home Premium, SP1

**VIPRE Antivirus 2016**

**Additional context**
[Add any other context about the problem here.]

**Comment by borzel** [comment]
All god, false Alarm!

https://www.virustotal.com/#/file/23f9ccfbde90d2e895590a2061832e48d6aba8d55119c4daac149ec6a654b7d7/detection
