### ISSUE TITLE
Missing Schema Files after install

### ISSUE THREAD

**Issue by devscott** [xcp-ng/xenadmin#127]
**Describe the bug**

2018-12-28 06:28:42,397 ERROR XenOvf.Utilities.Tools [20] - ValidateXmlToSchema Exception: Could not find a part of the path 'C:\Program Files (x86)\XCP-ng Center\Schemas\xml.xsd'.

Installed XenCenter, copied the files from that location, restarted and error went away. Would be nice if we could include these files with the installer.

**To Reproduce**
1. Tried to import an OVA file.

**Expected behavior**
Schema files to resolve

**XCP-ng Center:**
 - XCP-ng Center Version: 7.6.2.17
 - Desktop OS:

**Comment by borzel** [comment]
@devscott Please test with this and report back!
[XCP-ng-Center-7.6.2.18.msi.zip](https://github.com/xcp-ng/xenadmin/files/2747126/XCP-ng-Center-7.6.2.18.msi.zip)

**Comment by borzel** [comment]
ok, its available in our pre-release: https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.3-Preview1
