### ISSUE TITLE
Defining a specific MAC address during the XVA import wizard does not persist during import

### ISSUE THREAD

**Issue by De-Occultist** [xcp-ng/xenadmin#128]
Moved from https://github.com/xcp-ng/xcp/issues/109

XCP-ng version 7.6 using XCP-ng Center 7.6.0

- Import XVA specify the MAC address as aa:bb:cc:11:22:33 in the wizard
- Start the VM, check the Networking tab, the MAC address is a random MAC address.

I've tested import with 
`xe vm-import filename=xxx.xva preserve=true` and the MAC address is preserved.

But when exporting with XCP-ng Center 7.6.0, the import will begin immediately after the "Storage" selection in the"Import XVA" wizard. Changing the Network MAC address in the "Network" dialog will display the new MAC address but upon starting the VM it will revert back to the random MAC address it initially displayed in the "Import XVA" wizard.

**Comment by schulz-alexander** [comment]
**Problem**

Changes on the MAC adress in the import wizard are saved via https://github.com/xcp-ng/xenadmin/blob/4cd256f33cf0d605e05ae14c034c9ec5b11abc07/XenModel/Actions/VM/ImportVmAction.cs#L204

But `VIF.move` only changes the network properly, but not the MAC address. The new MAC address is showed in the xenadmins GUI, but on the first power on of the VM the old MAC address is used and showed.

**Solution**
a) Use the old way and delete and recreate the VIF. So also the MAC address is saved properly.
b) only if the MAC address is changed, use the old way

**Comment by schulz-alexander** [comment]
Upstream bug report: https://github.com/xenserver/xenadmin/issues/2433

**Comment by schulz-alexander** [comment]
merged to development and release-xcp-ng-8.0

**Comment by schulz-alexander** [comment]
It's now released: https://github.com/xcp-ng/xenadmin/releases/tag/v8.0.1.26
