### ISSUE TITLE
Problem creating template from preseed - XCP-NG center error

### ISSUE THREAD

**Issue by rj-dsl** [xcp-ng/xenadmin#129]
When trying to create VM from template (PV with preseed), XCP-NG center crashes..

Original problem here:
https://xcp-ng.org/forum/topic/813/problem-creating-templates-with-preseed/6

XCP-NG center error:
![screenshot-from-2019-01-10-16-39-39](https://user-images.githubusercontent.com/36693631/51002226-e79ec180-1532-11e9-8bd7-e39374f3d1ba.png)

**Comment by cocoon** [comment]
Hi,
I cannot do any test currently but it fails somehow to detect if for Installation Source you have entered something as DVD or URL.

Source is here:
https://github.com/xcp-ng/xenadmin/blob/master/XenAdmin/Wizards/NewVMWizard/Page_InstallationMedia.cs#L126

What did you use for the template? DVD or URL?
Would be good to have all steps written down that are needed to recrerate the problem.

**Comment by rj-dsl** [comment]
Hey :)

Thanks for checking up..

The preseed is on our dhcp server and is server over http on this path:
/var/www/preseed/virtual-ubuntu-16.04-server.cfg

I tried to access from a VM on one of my XCP-hosts, and the file is available, so its not the an access problem.. It worked when I used it in Xen Center 7.2, so I´m thinking it an XCP-NG specific problem..

As for how to recreate.. I converted the stock ubuntu 16.04 image cant comes with XCP from an HVM to a PV template. I then create a new VM, select our custom template, give it a name, and then at the "Installation Media" window, it crashes.. (As seen in attached screenshot)

![screenshot_1](https://user-images.githubusercontent.com/36693631/51754085-b2aa7700-20bb-11e9-8dd7-e63fea08b214.png)

Behavior is the same for our 18.04 template.

The advanced OS boot params in full are:
`console=hvc0 auto url=http://10.16.4.4/preseed/virtual-ubuntu-16.04-server.cfg locale=en_DK console-setup/layoutcode=dk netcfg/choose_interface=eth0`

Now I have absolutely no idear what the error is.. And theres no option for preseed installation through XO/XOA, so im kinda dead in the water right now..

If you want more info please let me know, Im more that willing to help resolve this issue..

**Comment by cocoon** [comment]
OK, in the screenshot I can see that no checkbox (DVD/URL) is checked.
But I see Text in the URL Textbox.

In XCP-NG Center there is an additional check:

eli = !hvm && m_template.PV_bootloader == "eliloader";

If using URL it requires the PV_bootloader  to be eliloader.

**Comment by rj-dsl** [comment]
Is that an arg I need to pass when creating the template? or How do I resolve that?

**Comment by cocoon** [comment]
https://wiki.xenproject.org/wiki/XCP_PV_templates_start

xe vm-param-set uuid=... PV-bootloader=eliloader

**Comment by rj-dsl** [comment]
I will test it out tomorrow and report back, but ty for our initial help :)

**Comment by cocoon** [comment]
I can at least recreate the problem, I get the same message.

I tried to remove HVP-boot-params and made a diff between the two XML-Files but I could not see the real problem.

**Comment by cocoon** [comment]
OK Problem found, it was the Disks entry:

xe template-param-remove uuid=$UUID param-name=other-config param-key=disks

Then it should be ok

**Comment by rj-dsl** [comment]
Okay, so Im able to create the VM now, but it give me an error on boot "Internal error: there is no bootable device".. But im not sure if that because it dosent get the boot images from the URL provided or whats going on.. But at least I am further now than a week ago.. So ty very much for your help.. If anyone else runs across new info regarding these issues, feel free to post here.
