### ISSUE TITLE
build script for dotnet-packages

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#13]
Hi,
first many thanks for your work on getting this ready in such a short time!

I made some changes to the Wiki regarding building the dotnet-packages with trying to be able to build as much as possible without modifications to the build.sh script (adding msbuild tools 2013 and 2015):
https://github.com/xcp-ng/xenadmin/wiki/How-to-build

Then I have seen you have already planned some changes to the build files:
https://github.com/borzel/dotnet-packages/commit/8e47e4e5c5c73ad6a5c7f9b9943bc69fdc7e0416

I was just thinking about the same because the only problem I think is that one would need to install Visual Studio 2013 for getting the c++ tools v120 as they are not available as separate download.

So I thought about adding an additional script like build_no_putty.sh and comment out the putty part only? 
What do you think?

**Comment by borzel** [comment]
Yes, in the meantime this would be good.

Later we should find out, why they build their own putty from sources instead of downloading a official putty. Spezial Citrix-Patches?

**Comment by borzel** [comment]
I would put these dotnet-packages into our repo and include all into our "big" buildscript. There is no need (for us) to have these sources elsewhere.

What's your opinion @cocoon @gangsterrapper22 @olivierlambert ?

**Comment by cocoon** [comment]
You mean to copy the files as a subfolder into xcp-ng/xenadmin?

The only thing is you loose the commit history but that is not a big issue I think.
If updating the files it could have a note about the commit id from where the files come.
Or you could add it as a submodule and use `git clone --recursive`.

**Comment by olivierlambert** [comment]
What should be the name of the repo?

**Comment by borzel** [comment]
Maybe "center-libs" ? hmm... naming is the hardest job...

--> xenadmin-libs ?

**Comment by borzel** [comment]
@olivierlambert I did screw up with the xenadmin-thirdparty-libs repo. I can not PR against the original https://github.com/xenserver/dotnet-packages because it is not forked :-|

So, can you please
* delete the actual xenadmin-thirdparty-libs repo
* fork https://github.com/xenserver/dotnet-packages
* add me as admin

Thanks!

**Comment by olivierlambert** [comment]
Done.

**Comment by borzel** [comment]
For now we have our own https://github.com/xcp-ng/dotnet-packages. Maybe in future things will change, but not now.
