### ISSUE TITLE
Remove vCPU Limit from UI

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#133]
https://github.com/xcp-ng/xcp/issues/131

**Comment by borzel** [comment]
closed because there is no limit in the UI.
The limit is in the template: https://github.com/xcp-ng/xcp/issues/131#issuecomment-460786118

**Comment by stormi** [comment]
Note that although more than 32 vCPUs work, above that there's no guarantee that a malevolent VM wouldn't be able to do nasty stuff to Xen, hence the 32 limit. Someone willing to document it in the wiki?
