### ISSUE TITLE
Enhancement Request: NFS4.1 support

### ISSUE THREAD

**Issue by MrMEEE** [xcp-ng/xenadmin#136]
Hi..

I have just gotten NFS4.1 support merged upstream and in XCP-NG..

Right now there is only an option for NFS4 in the client.. can we add an option for NFS4.1 as well??

**Comment by borzel** [comment]
Work in progress...

![grafik](https://user-images.githubusercontent.com/5782951/52493743-7c491d80-2bcc-11e9-8bf6-a4da44a6dda6.png)

**Comment by MrMEEE** [comment]
Cool :)

**Comment by borzel** [comment]
works (with current FreeNAS-11.2-RELEASE-U1 as Server):

![grafik](https://user-images.githubusercontent.com/5782951/52498334-d6e87680-2bd8-11e9-9c3e-952cf99d59dc.png)

**Comment by olivierlambert** [comment]
By the way, eager to know any perf diff between 3, 4 and 4.1 :)

**Comment by borzel** [comment]
me too

**Comment by MrMEEE** [comment]
Great job!!!

NFS3->NFS4 much better performance on small files

NFS4 -> NFS4.1 parallel NFS, giving generally better performance :)

**Comment by borzel** [comment]
Please test: https://github.com/xcp-ng/xenadmin/releases/tag/v7.6.3.21

**Comment by olivierlambert** [comment]
@MrMEEE I know the theory, but I asked for actual benchmarks ;)

**Comment by cocoon** [comment]
Damn that was quick ... 10 hours from question requesting a new feature NFS 4.1 to released installer with NFS 4.1 ... Friday ^^

**Comment by borzel** [comment]
I was on fire 🔥

**Comment by borzel** [comment]
Finally released with 8.0.0

**Comment by MrMEEE** [comment]
Cool ;)
