### ISSUE TITLE
Move Update.xml to separate repo

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#138]
* [x] create new repository: https://github.com/xcp-ng/xenadmin-updates
* [x] insert xml file: https://raw.githubusercontent.com/xcp-ng/xenadmin-updates/master/updates.xml
* [ ] change path in XCP-ng Center 7.6
* [x] change path in XCP-ng Center 8.0.0
* [x] change path in XCP-ng Center master

**Comment by schulz-alexander** [comment]
I changed the original update.xml on the master branch of xenadmin, so also the older 7.6 should find the update and show the notification.
