### ISSUE TITLE
Cannot connect to Citrix XenServer after rebranding

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#14]
Thanks to all the documentation and scripts about how to build and how to rebrand, I was able to successfully compile the whole XCP-NG Console.

One thing is broken now, it is not possible to connect to original XenServers anymore because of this check:
https://github.com/xcp-ng/xenadmin/blob/master/XenAdmin/MainWindow.cs#L894

**Branding.PRODUCT_BRAND:** XCP-ng
**master.ProductBrand:** XenServer

As a quick workaround I added an additional check
```
if (!Program.RunInAutomatedTestMode && !SameProductBrand(master) && master.ProductBrand() != "XenServer")
```

**Comment by borzel** [comment]
@cocoon please test again

**Comment by cocoon** [comment]
Funny thing: with the latest updated Visual Studio 2017 (15.6.5) I cannot build because of the error if unreachable code is present.

I am sure I did the same before without problems.

If you add a check like this it can be built:
```
bool unrestricted = true;
if(unrestricted) return true;
```

**Comment by borzel** [comment]
I tested against XenServer 7.2 -> works now

**Comment by cocoon** [comment]
Yes it working for me with 7.2 now, great 👍
