### ISSUE TITLE
Cloud-Config Parameters could not be retrieved

### ISSUE THREAD

**Issue by MikeDombo** [xcp-ng/xenadmin#143]
**Describe the bug**
Cloud-Config Parameters could not be retrieved when right clicking on a CoreOS VM properties and going to Cloud-Config Parameters tab. The Config drive template box is grayed out with the error "The cloud-config parameters could not be retrieved".

**To Reproduce**
1. Go to a CoreOS VM properties
2. Click on Cloud-Config Parameters

**Expected behavior**
Should be able to view and modify cloud-config drive.

**Hard-/Software involved:**
 - Host XCP-ng Version: 7.6
 - Client XCP-ng Center Version: 7.6.3
 - Desktop OS: Windows 10 insider preview 19h1.

**Additional context**

**Comment by cocoon** [comment]
Hi MikeDombo,

can you check the log files (/var/log/xensource.log) on your xcp-ng-servers for the following message:

```
Feb 11 08:02:18 YOURXENSERVER xapi: [debug|YOURXENSERVER|39540812 INET :::80|host.call_plugin R:31f57398ba97|audit] Host.call_plugin host = 'YOURHOSTUUID (YOURXENSERVER)'; plugin = 'xscontainer'; fn = 'get_config_drive_configuration'; args = [ vdiuuid: SOMEVDIUUID]
Feb 11 08:02:18 YOURXENSERVER xapi: [error|YOURXENSERVER|39540812 INET :::80|dispatch:host.call_plugin D:bea308b9d0af|backtrace] host.call_plugin R:31f57398ba97 failed with exception Server_error(XENAPI_MISSING_PLUGIN, [ xscontainer ])
Feb 11 08:02:18 YOURXENSERVER xapi: [error|YOURXENSERVER|39540812 INET :::80|dispatch:host.call_plugin D:bea308b9d0af|backtrace] Raised Server_error(XENAPI_MISSING_PLUGIN, [ xscontainer ])

```

Or any message regarding the Plugin "xscontainer".


For reference, the execution of that plugin is here:
https://github.com/xcp-ng/xenadmin/blob/master/XenAdmin/Wizards/NewVMWizard/Page_CloudConfigParameters.cs#L149

**Comment by MikeDombo** [comment]
I guess during the upgrade to one of the newer XCP-ng versions the plugin got removed. After installing xscontainer again it is working once more.
