### ISSUE TITLE
Remove health check from XCP-ng Center

### ISSUE THREAD

**Issue by fred974** [xcp-ng/xenadmin#144]
**Describe the bug**
When adding servers to the XCP-ng Center, we get prompt to enrol in the XCP-ng health check service

**To Reproduce**
1. Go to XCP-ng Center
2. Click on add a new server
3. See the prompt to enrol in the XCP-ng health check service

**Expected behavior**
This is a service done by Citrix, not removed from XCP-ng Center. and Should be removed from XCP-ng Center

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.

**Hard-/Software involved:**
 - Hardware: Dell PowerEdge C6200
 - Host XCP-ng Version: 7.6
 - Client XCP-ng Center Version: 7.6.3
 - Desktop OS: Windows 10 pro

**Comment by maxcuttins** [comment]
XCP-ng Center supports both XS and XCP.
So you can have several Pools in XS and other in XCP.

So this feature could be usefull to those that want still this feature at least on their XS pools.

I agree that users should not be warned to enrol in the health service if they have just a XCP pool.

**Comment by schulz-alexander** [comment]
I disalbed the HealthCheck completely and also the Transfer of Metadata and the Check if XenServer patches are availlable
