### ISSUE TITLE
Easy way to view a hosts logfiles

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#145]
* logfile browser?
* generate zip archive?
* other ideas?

**Comment by cocoon** [comment]
What about a **Log-Collector-Plugin**?

That could be developed separated from XCP-NG Center, but maybe automatically installed with it.
(Was thinking about that a few weeks ago, if an own plugin would be good for the zstd-export)

Then the Plugin could collect all the logs as an archive from the server(s) and maybe even do some simple parsing for ERROR or something like that and highlight them in red.
Similar to **CMTrace** (https://www.pei.com/2018/05/review-log-files-cmtrace/) or simply use that tool, saves time  to develop it.

I don't know if it would need an additional server-side plugin to collect the logs and create an archive, but I think so.

**Comment by olivierlambert** [comment]
I think there is already some stuff like that in XenCenter. Can you check the source and see what it calls? (in XAPI)

**Comment by cocoon** [comment]
Yes you're right, the bug tool seems to use this:
https://github.com/xcp-ng/xenadmin/blob/master/XenModel/Actions/ZipStatusReportAction.cs

have to search some more ...

**Comment by olivierlambert** [comment]
I'm very unfamiliar with XC source code so if you can point the XAPI call behind it, this will be also helpful for XO! :+1:

**Comment by cocoon** [comment]
A bit short of time, but found this:

https://github.com/xcp-ng/xenadmin/blob/master/XenModel/XenAPI/HTTP_actions.cs#L157

coming from here:

https://github.com/xcp-ng/xenadmin/blob/master/XenModel/Actions/Host/SingleHostStatusAction.cs#L80

**Comment by cocoon** [comment]
Yes, the status report is the feature and it collects much more than only some logs (db, rrds ...).
Additionally in the server properties is an option to set a remote log destination ... I have not used it, might be rsyslog.

![01-status-report](https://user-images.githubusercontent.com/1071741/52866962-19adcf80-3140-11e9-8935-7ee59501b9ed.png)

![02-status-report](https://user-images.githubusercontent.com/1071741/52866963-1a466600-3140-11e9-834a-efb454238dc5.png)

![03-log-dest](https://user-images.githubusercontent.com/1071741/52866965-1a466600-3140-11e9-83ac-9a1d5c943a16.png)

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
