### ISSUE TITLE
Cannot run when AppData is redirected

### ISSUE THREAD

**Issue by amaccuish** [xcp-ng/xenadmin#146]
**Describe the bug**
XCP-ng Centre won't run when AppData is redirected. An error is displayed

**To Reproduce**
1. Double-click XCP-ng icon on the desktop

**Expected behavior**
XCP-ng Centre opens.

**Screenshots / Logfiles**
Attached
[log.txt](https://github.com/xcp-ng/xenadmin/files/2898598/log.txt)

**Hard-/Software involved:**
 - Client XCP-ng Center Version: 7.6.3.20
 - Desktop OS: Windows Server 2016

**Comment by cocoon** [comment]
I see that it is redirected to a NAS UNC path?

I have no such environment currently to check my self, but I did one try that might help or not, let me know if this is working for you:
http://www.mediafire.com/file/7kblegi5zan8nzp/Debug_SaveConfig.zip

Don't use this build for serious work as it is a testbuild with some changes to the export function that will not work for you.
Just try if it will start and let you save the settings.

**Comment by amaccuish** [comment]
Thanks! That worked. I've attached a new log file since a message appears sometimes saying there has been an unexpected error. Otherwise, everything works as normal
[log.txt](https://github.com/xcp-ng/xenadmin/files/2954530/log.txt)

**Comment by cocoon** [comment]
Thanks for reporting back.

`a message appears sometimes saying there has been an unexpected error`

Is this message appearing in the GUI or only in the log file?

From the log I could not quickly identify from where it is triggered.
I added a branch if someone wants to dig deeper.

**Comment by amaccuish** [comment]
It came from the gui and told me to look in the log file.

**Comment by amaccuish** [comment]
Is there anything further I need to do?

**Comment by cocoon** [comment]
Hi, no I don't think there is anyhting you could add.

Would it be already of help if the first change would be integrated in the official release?
The other message would still appear, but I have currently no time to reproduce this error.

If the first change is enough, this only needs to be picked up for the next release by borzel as soon as he find some free time again.

**Comment by cocoon** [comment]
https://github.com/xcp-ng/xenadmin/commit/7795008abc10858bcf65a1b01a2a60d9a6f008d9

**Comment by amaccuish** [comment]
@cocoon sorry I didn't reply! Yes it would be great for the first change to be integrated. The other message maybe something to do with first run, as I haven't seen it since. Thanks again for your help!

**Comment by schulz-alexander** [comment]
Note to myself: TODO: port fix to development

**Comment by schulz-alexander** [comment]
@amaccuish @cocoon
I redirected my c:\users\xxxxx\appdata\roaming to my NAS, but I can not reproduce this. How to trigger the bug?

I want to reproduce your issue, so we fix a thing we also understand ;-)

**Comment by amaccuish** [comment]
So using group policy, my appdata roaming is redirected to a Samba4 server. The error I get is the first message in this thread :)

**Comment by schulz-alexander** [comment]
@amaccuish can you please post the complete steps you did? I want to reproduce it exactly.

**Comment by amaccuish** [comment]
I don't understand what you mean by exact steps? After installing the admin centre, I open it but before the main window appears the error comes up about my settings file being corrupted.

**Comment by schulz-alexander** [comment]
I want to reproduce your situation, so what did you exactly. In no posting you explained how you setup your folder redirection. Which settings did you in that GPO? Which SAMBA version?

**Comment by amaccuish** [comment]
GPO: User Configuration -> Policies -> Windows Settings -> Folder Redirection -> AppData (Roaming)
Samba 4.10.4

Literally a completely standard folder redirection scenario, no offline files.

**Comment by schulz-alexander** [comment]
@amaccuish Is that in an AD environment? Or in local Group Policy Editor?

**Comment by schulz-alexander** [comment]
@amaccuish Closing due to no feedback. Please reopen if needed!

**Comment by amaccuish** [comment]
> @amaccuish Is that in an AD environment? Or in local Group Policy Editor?

That's in an AD environment. Sorry for the delay!

**Comment by amaccuish** [comment]
Fixed.

It was a conflict with a setting on the Samba server in the vfs_catia module that is designed to help macOS clients, but interferes with file naming.

**Comment by schulz-alexander** [comment]
Thanks for the feedback!
