### ISSUE TITLE
Can't create local iso repository 

### ISSUE THREAD

**Issue by kagou** [xcp-ng/xenadmin#149]
Please add the option to create local ISO repository

**Comment by olivierlambert** [comment]
Thanks for your feedback. As a 100% community maintained project, contributions are welcome :+1: 

FYI, this feature is already available in Xen Orchestra :wink:

**Comment by schulz-alexander** [comment]
we will not work on that

**Comment by DoTheEvo** [comment]
I see option to add SMB or NFS ISO shares, but cant create **local** ISO storage?

![1735409716](https://github.com/user-attachments/assets/667d40ff-4960-4678-a2c3-c46bff344a32)

**Comment by olivierlambert** [comment]
It's available in XO, but not in XCP-ng Center. Last contributor said "won't do" and the new one seems pretty busy. If he's OK, he will re-open it. But keep in mind: it's only community maintained :)
