### ISSUE TITLE
Cross-Pool Copy VM Internal Error Xmlrpc_Client.Connection_reset

### ISSUE THREAD

**Issue by prowebuk** [xcp-ng/xenadmin#151]
Attempting to copy a VM between XCP-ng 7.6 pools using the copy vm function of XCP-ng Center but all target pools in the destination select list show the following error:

[pool name] - Internal Error Xmlrpc_Client.Connection_reset

The pools are all XCP-ng 7.6 and are available and manageable from the XCP-ng Center object tree.

Thanks

**Comment by olivierlambert** [comment]
1. Can you post a screenshot of the "copy" button?
2. Does it work with `xe` or Xen Orchestra? (to be sure it's a XCP-ng Center issue or a problem on your hosts)

**Comment by schulz-alexander** [comment]
Please feel free to reopen if needed.

**Comment by Damacia** [comment]
HI,

I am having the same issue when trying to move VMs from xcp-ng v8.1 to xcp-ng v8.2.1
![Screenshot 2023-05-28 225818](https://github.com/xcp-ng/xenadmin/assets/134884701/b8325642-19a6-4006-ae52-8582ab7dcd1f)

**Comment by olivierlambert** [comment]
Please try with a supported client and report. If it works in Xen Orchestra or via xe CLI, then it's a real XCP-ng Center bug (however, I'm not aware of any active contributor now, since it's also not officially supported)
