### ISSUE TITLE
Linux/Cross platform client

### ISSUE THREAD

**Issue by declanmarks** [xcp-ng/xenadmin#154]
Is there any plans for work in progress to create xenadmin cross platform such as running on Linux. There seems to be a project but hasn't had much activity for about a year. This would be really nice. It is amazing that the client doesn't even support macOS.

**Comment by olivierlambert** [comment]
See https://github.com/xcp-ng/xenadmin/issues/44

The currently recommended cross-platform client is Xen Orchestra, accessible from your web browser.

**Comment by schulz-alexander** [comment]
@declanmarks it's already "in progress": https://github.com/xcp-ng/xenadmin/issues/23
