### ISSUE TITLE
XCP-NG Center not updating topology (cores-per-socket) when reducing vCPU count

### ISSUE THREAD

**Issue by rudolphohanick** [xcp-ng/xenadmin#155]
**Describe the bug**
When reducing the number of vCPUs a VM has in XCP-NG Center 8.0.0, the topology automatically updates to something sensible but when you come to start the VM, XCP-NG hasn't saved this setting and throws an error:

_The value 'VCPUs_max must be a multiple of this field' is invalid for field 'platform:cores-per-socket'_

Going back into the settings shows the original value for the Topology prior to changing the vCPUs. 

**To Reproduce**
1. Right-click on a VM with multiple vCPUs and go to _Properties_
2. Select the _CPU_ option
3. Reduce the _Maximum number of vCPUs_ option
4. Note the _Topology_ automatically changes
5. Hit _OK_ to save changes
6. Start VM, get error shown above due to _Topology_ not updating

**Expected behavior**
It is expected the topology displayed will be saved

**Software involved:**
 - Host XCP-ng Version: 7.6
 - Client XCP-ng Center Version: 8.0.0.24

**Comment by schulz-alexander** [comment]
@rudolphohanick 
* Can you provide a screenshot of the error/the values?
* From which value exactly to which new value did you decrease the vcpu count?
* Can you reproduce this on different VM's?
* Bonus question: Can it be reproduced with XS/CH 8.0 and XCP-ng Center 8.0.0?

**Comment by schulz-alexander** [comment]
closed because no feedback, please reopen if needed
