### ISSUE TITLE
Feature Request: Ability to set Host clocksource / Xen boot options via XenCenter

### ISSUE THREAD

**Issue by sammcj** [xcp-ng/xenadmin#164]
It would be great if you could set the Xen boot options, or at least the clocksource via XenCenter.

A bit like how you can configure things like GPU pass-through, the iSCSI IQN etc... it could be an option to either select from available clock sources (`xen`, `tsc`, `hpet`, `acpi_pm`) or at least pass through Xen hypervisor command line boot options (which will allow you to do this).

I would suggest this could be under a tab such as 'Advanced' or 'Advanced Boot Options', perhaps with a warning that this area is for advanced use only and could cause your system not to boot if you're unaware of what you're doing.

At present to set Xen boot options (including the clock source) you must run the following (for example to set the clock source to `tsc`) on each host in the pool:

```
/opt/xensource/libexec/xen-cmdline --set-xen clocksource=tsc
/opt/xensource/libexec/xen-cmdline --set-xen tsc=stable:socket
```

and reboot.

This stems from https://xcp-ng.org/forum/post/12154

Not high priority, but would be nice to have more advanced control.

**Comment by olivierlambert** [comment]
I think it might be needed to create a XAPI plugin first, then it would be possible to expose it to clients (XO/XC/xe)

**Comment by sammcj** [comment]
Ah right I didn’t realise that XL commands weren’t exposed over the XAPI, I should really read the api docs 😂

Totally understand if you want to close as a ‘too hard for now, maybe in the future’ 

--
Sam McLeod

**Comment by olivierlambert** [comment]
Everything that's not exposed via XAPI can't be in the clients. I would say it's just not the place for this issue, it would be in xcp repo aksing for XAPI to expose this settings.

**Comment by cocoon** [comment]
@olivierlambert I was often thinking about a central xcp-ng-plugin that would be bundled with XCP-ng server to easily extend and maintain additional features without the need to really extend the xen api.

It is much quicker to adjust and fix.

(https://github.com/xcp-ng/xenadmin/wiki/Create-a-custom-Server-Plugin-%28example%29)

**Comment by sammcj** [comment]
that's a neat idea...

**Comment by olivierlambert** [comment]
Yeah but I don't want to create an open door to anything (or even worse, being able to pass system commands directly).

Having small dedicated pieces of code instead of one big bunch of random stuff is preferable. I'm telling this because I know who we'll maintain it :smile:

**Comment by schulz-alexander** [comment]
I think this too much for our little team. Please reopen, if someone has a good idea.
