### ISSUE TITLE
XCP-ng Center 8 unable to launch putty

### ISSUE THREAD

**Issue by tuzzmaniandevil** [xcp-ng/xenadmin#165]
**Describe the bug**
When trying to use the `Open SSH Console` I get an error stating `XCP-ng Center has encountered a problem launching PuTTY.` I have PuTTY 0.71 32bit and 64bit installed.

**To Reproduce**
1. Go to a VM
2. Click on Console
3. Click on Open SSH Console

**Expected behavior**
I would expect to see PuTTY open or at least provide a meaningful error as to why it can't open PuTTY i.e. not found at this location.

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/3378330/58452709-6441dd80-816c-11e9-8e37-23b92afb3bb0.png)

**Hard-/Software involved:**
 - Host XCP-ng Version: 7.6
 - Client XCP-ng Center Version: 8.0.0.24 64-bit
 - Desktop OS: Windows 10 17763

**Comment by schulz-alexander** [comment]
putty is not provided with XCP-ng Center. If you want to use it, copy the putty exe into the program dir of XCP-ng Center.

**Comment by thorcraftit** [comment]
> putty is not provided with XCP-ng Center. If you want to use it, copy the putty exe into the program dir of XCP-ng Center.

Put that in the error message. No one is going to intuitively know that. I would have saved me scouring the internet for this message.

**Comment by schulz-alexander** [comment]
Good point. Why did myself not give me this idea :-/

**Comment by schulz-alexander** [comment]
@thorcraftit better this way?

![grafik](https://user-images.githubusercontent.com/5782951/73139701-03f39a80-4071-11ea-88b3-6335d4061219.png)
