### ISSUE TITLE
Can't move VDISK within Local SR

### ISSUE THREAD

**Issue by Petahh** [xcp-ng/xenadmin#166]
Dear developers,
Relatively straight forward problem. I can't move VDISK between Local SRs.
No idea if this was intention to disable in higher versions or a bug.
This behavior is not observed in Version 7.6.1.
I can observe this in version 7.6.3 upwards till latest release.

![59661548-58fe3280-91ab-11e9-98c9-54c293186b51](https://user-images.githubusercontent.com/7292374/60042452-0c8c8880-96be-11e9-8e3f-c4aafd892ee3.jpg)

**Comment by schulz-alexander** [comment]
It's a "feature" from upstream, but I did not look at it yet.

Can you or someone else try to find the relevant commit or the reason for that?

**Comment by olivierlambert** [comment]
Is it working in Xen Orchestra? (to know if there is a technical reason behind this).

**Comment by schulz-alexander** [comment]
it is workin in XO, I did this in the last weeks.

**Comment by cocoon** [comment]
https://github.com/xenserver/xenadmin/issues/2454

https://github.com/xenserver/xenadmin/commit/660eab5d998b6361e212cfbcfdc2940ea2424ef5


Just had a quick search, these were the obvious ones.

**Comment by Petahh** [comment]
Their answer on upstream makes no sense (at least not to me). I'm not using pools, rather standalone server, Move VM doesn't help at all. 

I'm using ZFS FS type and I'm adding my SR with:

`xe sr-create host-uuid=X name-label=X type=file other-config:o_direct=false device-config:location=X` 

Plus I have few EXT4 added with similar method `type=file`, just reworking it and will be adding them with:

`xe sr-create type=ext4 name-label=mySR host-uuid=<host_UUID> device-config:device=/dev/sdX`

Not sure if that will help in any way.

Fact is that lack of this option is keeping me from updating from 7.6.1 XCP-ng Center.

**Comment by schulz-alexander** [comment]
@Petahh I added a comment to maybe clear the situation on CITRIX side so they can understand what you want to do: https://github.com/xenserver/xenadmin/issues/2454#issuecomment-505226755

**Comment by schulz-alexander** [comment]
TODO: Check with CITRIX Hypervisor 8.0 and XenCenter 8.0

**Comment by cocoon** [comment]
I can add that if you create a disk manually in a local SR you are allowed to move it.
Then I created a CentOS 7 VM from the template, and the problem occurs.
(XCP-NG + Center 8)

The message comes from here:
https://github.com/xcp-ng/xenadmin/blob/development/XenAdmin/Controls/SrPickerItem.cs#L131

and the error comes from here:
https://github.com/xcp-ng/xenadmin/blob/development/XenAdmin/Controls/SrPickerItem.cs#L312

recent changes:
https://github.com/xenserver/xenadmin/commits/master/XenAdmin/Controls/SrPickerItem.cs


![004-No-Pool_XCP-NG-C-8](https://user-images.githubusercontent.com/1071741/60076714-8bb6a680-9728-11e9-83a7-8b24e95635fc.png)
![005-No-Pool_XCP-NG-C-8-VM](https://user-images.githubusercontent.com/1071741/60076716-8bb6a680-9728-11e9-941a-993d6fa3517d.png)

**Comment by schulz-alexander** [comment]
Issue should be solved: https://github.com/xenserver/xenadmin/pull/2465

**Comment by schulz-alexander** [comment]
Fix is included in https://github.com/xcp-ng/xenadmin/releases/tag/v99.99.99.27
