### ISSUE TITLE
Bond and (maybe VLANs) are disconnected?

### ISSUE THREAD

**Issue by MrMEEE** [xcp-ng/xenadmin#169]
Hi

After creating a bond, and also doing VLANs on top of the bond, I have noticed that the bond is being reported as disconnected in XenAdmin, but as connected in the CLI..

The bond and vlans are working fine, but this means that I can't use them for migration???

What is going on here??

/Martin

![disconnected](https://user-images.githubusercontent.com/768031/60692327-bd243480-9ed5-11e9-9efe-758ba957bc4f.png)
![cli](https://user-images.githubusercontent.com/768031/60692330-c01f2500-9ed5-11e9-8e5d-2839e3d0d32c.png)
![select](https://user-images.githubusercontent.com/768031/60692346-e218a780-9ed5-11e9-90e8-80a9493375db.png)

**Comment by schulz-alexander** [comment]
Can you please test with the lastest release 20.03.00? It loaded with many changes from upstream.

--> https://github.com/xcp-ng/xenadmin/releases/tag/v20.03.00.29

**Comment by schulz-alexander** [comment]
we will not work on that
