### ISSUE TITLE
Can't move vm between single hosts

### ISSUE THREAD

**Issue by fraggan** [xcp-ng/xenadmin#170]
I'd move some vms from one single host onto another single host, no problems. Now when I tried to move them back I couldn't. In the window were I choose the destination it say "Cannot restore this vm because it would create a duplicate".

Forum post: https://xcp-ng.org/forum/topic/1657/can-t-move-vm-between-single-hosts

**Comment by schulz-alexander** [comment]
@fraggan please test with the latest release of XCP-ng Center: https://github.com/xcp-ng/xenadmin/releases/tag/v8.0.1.26

**Comment by fraggan** [comment]
Ah forgot to answer here, posted an answer in the forum :) I have tried with the newest Xcenter and I also updated the hosts and reboot. Still same problem.

**Comment by schulz-alexander** [comment]
@fraggan can you please recheck with the latest nighlty build? https://github.com/xcp-ng/xenadmin/releases/tag/v99.99.99.27

**Comment by fraggan** [comment]
Not sure I can reply but I'll try.
It was a while I had that problm, I'm not sure how I fixed it but I think I got some help from Oliver. So as of now there aren't any problem with that. Altough I don't move them much. But I'll try the new xcenter client anyways =)

/regards
Fredrik

**Comment by schulz-alexander** [comment]
Closed, please reopen if needed.
