### ISSUE TITLE
The "Auto-boot VM" function not working XCP-ng Center v8

### ISSUE THREAD

**Issue by kbalicki** [xcp-ng/xenadmin#172]
Boot Options tab for VM: Auto-boot: Yes

After server (re) start VM does not start and has to be started manually.

**Comment by schulz-alexander** [comment]
Which XCP-ng Center version exactly?

**Comment by kbalicki** [comment]
> Which XCP-ng Center version exactly?

8.0.0

**Comment by kbalicki** [comment]
8.0.1 - same problem

**Comment by DPerkunas** [comment]
Confirming same issue for 8.0.0, haven't tried 8.0.1 yet.

**Comment by schulz-alexander** [comment]
Maybe: need to set the general autoboot parameter for the whole server, not only for the VMs itself

**Comment by schulz-alexander** [comment]
same as here: https://github.com/vatesfr/xen-orchestra/issues/879

**Comment by speedy01** [comment]
> same as here: [vatesfr/xen-orchestra#879](https://github.com/vatesfr/xen-orchestra/issues/879)

This may be the case with v8.0, but 8.1 may be a different issue.

8.0 to 8.1 upgrade via yum went well without an issue, but autostart of the vm does not work. Auto start worked fine with 8.0.
I confirmed that autostart is set to TRUE on the pool and on the vm itself using
xe pool-param-get uuid=<pool_uuid> param-name=other-config param-key=auto_poweron
xe vm-param-get uuid=<vm_uuid> param-name=other-config param-key=auto_poweron

Not sure what else to check...but will be happy to provide any additional information

**Comment by schulz-alexander** [comment]
Its relatively difficult to set the autoboot parameter for the pool if I'm in the vm context. More investigation is needed.

**Comment by stormi** [comment]
Autostart of VMs in 8.1 updated via yum from 8.0 has been fixed since in XCP-ng directly, if that's the same issue.

**Comment by schulz-alexander** [comment]
@stormi no, it's an internal one

**Comment by kbalicki** [comment]
Is there some solution for this, or still nothing?

**Comment by olivierlambert** [comment]
For me, it's working on XCP-ng 8.1 with Xen Orchestra. Are you on 8.0?

**Comment by kbalicki** [comment]
> For me, it's working on XCP-ng 8.1 with Xen Orchestra. Are you on 8.0?

I do not use Xen Orchestra, and problem is still there :(

**Comment by HeMaN-NL** [comment]
What is your xcp-ng version and what steps have you done to enable it?

**Comment by Machine22** [comment]
Reporting on the same issue i am using the latest version of XCP-ng with xen center. Am facing the same issue right here, not only does pfsense not auto start on Xen server reboot but as well my other Windows 7 machine running Plex that is attached to Pfsense's LAN. Could it be an issue with Xcp or the VMs in particular are set up wrongly with in xcp though i highly doubt.
Anyone with a solution kindly pass it on. Thanks in Advance

**Comment by olivierlambert** [comment]
Can you try with Xen Orchestra? I just tested it here and it works.

**Comment by stormi** [comment]
I think this whole bug report is about XCP-ng Center, not XCP-ng or Xen Orchestra. I'm pretty sure it works in Xen Orchestra indeed.

**Comment by olivierlambert** [comment]
I'd like to be sure it's purely *XCP-ng Center* related, that might help to find the root cause :+1:

**Comment by kbalicki** [comment]
> What is your xcp-ng version and what steps have you done to enable it?

XCP-ng 8.1 + XCP-ng Center 20.04,00

XCP-ng Center: VM -> Properties -> Boot Options - ? Autostart on server boot
Rebooting server did not help either.

**Comment by kbalicki** [comment]
> I think this whole bug report is about XCP-ng Center, not XCP-ng or Xen Orchestra. I'm pretty sure it works in Xen Orchestra indeed.

Will test it when have some free time. My XCP-ng server is behind NAT, and it will take a moment to reconfigure everything, so it will be publicity available, so I can use XOA quick deploy.

**Comment by kbalicki** [comment]
> I'd like to be sure it's purely _XCP-ng Center_ related, that might help to find the root cause 👍

Confirmed, autostart works ok with Xen Orchestra, so it is XCP-ng issue.

**Comment by stormi** [comment]
> > I'd like to be sure it's purely _XCP-ng Center_ related, that might help to find the root cause +1
> 
> Confirmed, autostart works ok with Xen Orchestra, so it is XCP-ng issue.

XCP-ng *Center*

**Comment by olivierlambert** [comment]
> > I'd like to be sure it's purely _XCP-ng Center_ related, that might help to find the root cause +1
> 
> Confirmed, autostart works ok with Xen Orchestra, so it is XCP-ng Center issue.

Ah nice! Thanks :+1:

**Comment by Alphaprot** [comment]
Also can confirm that it is XCP-ng Center related, see [XCP-ng 8.1.0 - vm autostart not working](https://github.com/xcp-ng/xcp/issues/450#issue-738503214)

**Comment by steinbitglis** [comment]
Is there any workaround for this, other than installing xen orchestra?

**Comment by M-Covrig** [comment]
Perhaps you need to update to the latest xcp-NG center, and it should work. I'm using v20.04.01. I would suggest to use both xcp-ng center and xoa(even the free version is doing the job). Or you can ask for an extension to XOA license, the lads are very helpful. Cheers

**Comment by steinbitglis** [comment]
It seems like 'xe pool-param-set' and 'xe vm-param-set' worked. I'm new to XCP-ng, and apart from this auto-boot issue, I like it a lot.

**Comment by M-Covrig** [comment]
Yes it is nice and stable, we are using this for our organisation in the last 2 years nearly, and I'm delighted. Still there's a lot to learn... :). Forgot to mention, the only issue encountered was the LVM limitation to max 4TB if I remember correctly.

**Comment by schulz-alexander** [comment]
we will not work on that

**Comment by schulz-alexander** [comment]
follow up and information: https://github.com/xcp-ng/xenadmin/issues/211#issuecomment-1877098544
