### ISSUE TITLE
Snapshot Schedules not showing 'Last Run' date

### ISSUE THREAD

**Issue by scollonp** [xcp-ng/xenadmin#173]
**Describe the bug / How to Reproduce**
When a pool is selected under "Infrastructure" and you choose 'Pool > VM Snapshot Schedules' from the menu, the GUI window that is opened stated "Not yet run" under 'Last Run' schedule for all schedules, even if the schedule HAS run (as can be seen in notifications and by visiting the snapshots themselves under "Objects").

**Expected behavior**
We should actually be seeing the correct 'Last Run' date for the schedule(s).

**Screenshots / Logfiles**
![snapshots](https://user-images.githubusercontent.com/15896775/64186395-a7e06d80-ce66-11e9-8acf-ac8896a6709b.png)

**Hard-/Software involved:**
 - Hardware: Dell OptiPlex 7010
 - Host XCP-ng Version: 7.6
 - Client XCP-ng Center Version: 8.0.0
 - Desktop OS: Windows 7

Version of XCP-ng seems to be irrelevant.

**Comment by olivierlambert** [comment]
Personally, I would discourage the use of this feature within XCP-ng Center. There's no VDI chain healthcheck, there no efficient way to show that's it's running in the background, and we have reports of breaking XCP-ng storage due to the fact it can be setup and forgotten later, causing massive snapshots without chain checks. And there's no report on the status of the operation.

I already had 3 supports tickets about full SRs or infinite coalesce due to this "feature" inside XCP-ng Center.

**Comment by scollonp** [comment]
> Personally, I would discourage the use of this feature within XCP-ng Center. There's no VDI chain healthcheck, there no efficient way to show that's it's running in the background, and we have reports of breaking XCP-ng storage due to the fact it can be setup and forgotten later, causing massive snapshots without chain checks.

But what if the particular pool is not using Xen Orchestra - for example, this particular pool is managed by one person, myself. It contains some backup servers, a clonezilla server, a wiki and some other production stuff associated with our much bigger pool, that does use Xen Orchestra (community edition) - in fact XO for the large pool is run off one of the VMs in this smaller pool.

I use XCP-ng Center purely to create new VMs and add them to the snapshot schedule. Aside from not showing the "Last Run" date, the snapshot schedules have been working just fine. I've successfully restored VMs and everything. Our SR is HUGE (48TB) and I've limited each VM to a max of 4 snaphots, which it seems to be doing just fine.

**Comment by olivierlambert** [comment]
Then you are exposed to potential big issues on the SR (chain length etc). This feature is dangerous and Citrix won't care, that's all I said. I'm not "judging" or answering the initial issue (sorry for that!), if I were you I would avoid using it. If I don't see why not using XO for this pool in particular, knowing you have a solution that works better for that, it's entirely up to you, no worries :)

**Comment by scollonp** [comment]
We just never considered using XO on this pool because the XCP-ng Center tool was in use form day one. I would be curious to see what the author thinks of this chain length issue you mention, to be honest it's the first time I've heard of it (any links please for more info?). Also, it's worth noting we are using only XCP-ng on the backend, no XenServer instances left in any of the pools.

**Comment by schulz-alexander** [comment]
I also would not use this feature. But for compatibility reasons we keep it until we decide to remove it ;-)

**Comment by schulz-alexander** [comment]
we will not work on that
