### ISSUE TITLE
Can not connect locally

### ISSUE THREAD

**Issue by Diamondog** [xcp-ng/xenadmin#174]
I have installed Xcp-ng on a VM to test it and see if I want to put it into operation on my dell server. However after installing it and trying to connect to it locally via a local ip such as 192.168.2.100 the xcp-ng server is not answering. my local desktop unit has a ip of 192.168.1.44 but the server is .2.100 so what I did was make the xcp-ng server 1.100 when I did that the server was not able to ping out and I was not able to connect to it via Xcp-ng center. Was wondering if anyone could tell me what I am possibly doing wrong and if the issue is on the desktop NG center side or the NG server side. Thanks to all for the help in advance.

**Comment by olivierlambert** [comment]
Hi, can you tell us more about what was your issue?
