### ISSUE TITLE
XCP-ng Center 8.0.1 'Forgets' Window Position & Size When Placed Near Edge of Display

### ISSUE THREAD

**Issue by amp88** [xcp-ng/xenadmin#177]
When XCP-ng Center 8.0.1 is placed near the edge of a display and closed, the next time it's run it  'forgets' the last window position and size it had before it was closed.

Steps to reproduce the behaviour:
1. Open XCP-ng Center 8.0.1 
2. Move the XCP-ng Center window to just inside the top left corner of your display (or the top left corner of the leftmost display in a multi-monitor setup).
3. Close XCP-ng Center
4. Open XCP-ng Center
5. Its window position and size are reset to default values.

XCP-ng Center should be able to restore the window position and size, as long as they are legal values (i.e. the window location and size falls within the bounds of an active display).

However, it appears the values for WindowLocation and WindowSize stored in the 'user.config' file when XCP-ng Center exits are not correct. When the window is moved to within a couple of pixels of the top left corner of the display, the stored WindowLocation will have a negative x value. I suspect this may be as simple as having a border around the main window, which increases the effective window size, but I'm unable to test this at the moment. The WindowSize property in 'user.config' also appears to be larger than the window was when XCP-ng Center was closed (by 15 pixels in width and 8 pixels in height, I believe).

Desktop OS: Windows 10 Pro 1903
XCP-ng Center version: 8.0.1.26 and Nightly/dev build 99.99.99.27

**Comment by schulz-alexander** [comment]
~~can you please test again with the latest nightly 99.99.99.28 ?~~
I can confirm, it's a bug :-/

**Comment by schulz-alexander** [comment]
fixed: https://github.com/xcp-ng/xenadmin/commit/efc7824e7b4528fcf356cd4b0dce9e2aaa80943b

If the window was maximized or the values are outside of the boundaries of the screen, XCP-ng Center will be restored maximized.

The more advanced solution is to check the "unvisible" border. But this depends on the exact windows theme I think.

If you need a more advanced solution, please open a new ticket :-)
