### ISSUE TITLE
choco search xen   does not return xcp related packages

### ISSUE THREAD

**Issue by rjt** [xcp-ng/xenadmin#180]
**Describe the bug**
Using the chocolatey.org package management software, i want to get the latest version of xencenter for xcp-ng or xenadmin xcp-ng Center and install it.  So i search for xen, but only find Citrix related software packages:

[choco](https://chocolatey.org/) search xen
[xenserver-backup](https://chocolatey.org/packages/xenserver-backup#releasenotes)
[citrix-xenserver-sdk](https://chocolatey.org/packages/citrix-xenserver-sdk)
[xencenter](https://chocolatey.org/packages/xencenter) 
... and some others
```
PS C:\Users\Public> choco search xen |measure
Count    : 58

```
**To Reproduce**
1. Go to 'powershell.exe or cmd.exe'
2. Enter  'choco search xen'
3. Look for any 'xcp' related packages
4. Citrix related packages are found, but no [xcp-ng.org](https://www.xcp-ng.org/)
```
PS C:\Users\Public> choco search xcp
Chocolatey v0.10.15
0 packages found.
PS C:\Users\Public>

```
**Expected behavior**
XCP-NG Center should be added as a package to chocolatey.org package list so that any end users can install easily.  Anyone searching for xen should see xcp analogous packages, raising awareness.

**Hard-/Software involved:**
 - Desktop OS: [e.g. Windows 10 1909]
 - [chocolatey v0.10.15](https://chocolatey.org/)

**Additional context**
chocolatey is not nearly as powerful as yum or apt or brew or pip or any other form of package manager, but when forced to use Windows....

**Comment by schulz-alexander** [comment]
If someone has time to package it, go ahead :-)

**Comment by schulz-alexander** [comment]
I close the issue, because its not really a "true" XCP-ng Center issue.
