### ISSUE TITLE
XCP-ng Center v20.03.00 on startup briefly shows all tabs before connecting to servers.

### ISSUE THREAD

**Issue by ghost** [xcp-ng/xenadmin#181]
**Describe the bug**
When starting XCP-ng Center version v20.03.00, it briefly flashes/shows all tabs just before connecting to servers.

**To Reproduce**
1. Start XCP-ng Center
2. Notice just before connecting that all the tabs in the main pane are showing.

**Expected behavior**
All tabs in the main pane should not flash up during server connection.

**Screenshots / Logfiles**
See below for screen shot.

**Hard-/Software involved:**
 - Hardware: Windows VM
 - Host XCP-ng Version 8.0
 - Client XCP-ng Center Version: v20.03.00
 - Desktop OS: Windows 8.1 Pro

**Additional context**
Added a screenshot showing this behavior. Note: this is not a showstopper, it is more to notify the maintainer of this anomaly.
![xcp-ng-center-startup-anomaly](https://user-images.githubusercontent.com/52837806/76869636-fbcd0580-683e-11ea-82f8-dcf7816d88c1.png)

**Comment by schulz-alexander** [comment]
hmm... didn't notice this on Windows 10 Pro at home and at work.

Maybe only on Windows 8.1?

**Comment by schulz-alexander** [comment]
ahhh... I saw it, it was a blink of an eye long ...

**Comment by ghost** [comment]
@borzel did not think it was a big deal so I would not care if you scrapped it altogether. I didn't want to bother you with this but I thought you may want to know about it. Just wanted to say thanks a lot for all the work you did on this to port it to the XCP-ng project and the newer Visual Studios. Even Citrix didn't do that! I know you don't get many kudos for being the lone wolf on this project but I believe as you until XO gets a decent presentation layer, it is nice to have a fallback -- thanks again!

**Comment by schulz-alexander** [comment]
we will not work on that
