### ISSUE TITLE
Do not enable the Windows Update feature for guest tools by default

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xenadmin#182]
We have noticed that although the Windows guest templates do not enforce `has-vendor-device` to true, XCP-ng Center does when a VM is created.

See https://github.com/xenserver/xenadmin/blob/065e8bd7721547a000925d24c739889abf2358f0/XenModel/Actions/VM/CreateVMAction.cs#L260

When it detects that the license allows it, it automatically enables the option. Enabling this option should be a conscious user choice because it makes installing our own guest drivers much more difficult and leads to situations where users ignore that Citrix drivers got installed automatically and mix them with ours.

It seems important to me to disable this automatic behaviour in XCP-ng Center.

**Comment by schulz-alexander** [comment]
Did a little research. At least XCP-ng Center does all right (from its implementation view)

The value of **has-vendor-device** of the template is ignored and the value from **recommendations -> has-vendor-device** is used:

```
 xe template-param-list uuid=UUID-OF-WINDOWS10-TEMPLATE

...
 recommendations ( RO): <restrictions><restriction field="memory-static-max" max="1649267441664"/><restriction field="vcpus-min" min="2"/><restriction field="vcpus-max" max="32"/><restriction field="has-vendor-device" value="true"/><restriction field="supports-bios" value="yes"/><restriction field="supports-uefi" value="yes"/><restriction field="supports-secure-boot" value="yes"/><restriction max="255" property="number-of-vbds"/><restriction max="7" property="number-of-vifs"/></restrictions>
...
```
@stormi, @olivierlambert so what does XO at this stage? I ask to implement it the same way here - at least try to :-)

**Comment by olivierlambert** [comment]
Ping @julien-f 

I think we just ignore it.

**Comment by julien-f** [comment]
I have no idea what this value does, and XO has no special handling for it.

**Comment by olivierlambert** [comment]
As the issue title says: it enable Windows Update to download Citrix drivers. Like we do in Advanced tab.

**Comment by julien-f** [comment]
I see, I stand by my previous comment: XO does not enable it on creation.

**Comment by olivierlambert** [comment]
So we should remove it from XCP-ng Center anyway.

**Comment by stormi** [comment]
I agree. I was not aware of `recommendations` fields and they seem something we should consider in XO to improve the default parameters at VM creation. However in the case of the Windows Update feature it's better to not enable it in XCP-ng and let users enable it manually if they want to.

**Comment by olivierlambert** [comment]
@stormi I think we already use some fields for memory etc.

**Comment by schulz-alexander** [comment]
we will not work on that
