### ISSUE TITLE
Bug memory tab with dynamic memory missing url

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#184]
**Describe the bug**
Reported in the forum here:
https://xcp-ng.org/forum/topic/2804/yum-upgrade-8-0-to-8-1-vm-memory-error/

looks like a bug introduced by removing the Citrix-urls:
https://github.com/xcp-ng/xenadmin/commit/b2201f6a62303705a465f5a06bc7e3507c088f68#diff-07eabd7f8066c4f11a4c37b01b68cd39L192

root cause might be here:
https://github.com/xcp-ng/xenadmin/blob/development/XenAdmin/TabPages/BallooningPage.cs#L468

just compiled a build to try to see if commenting this will fix the error.

**To Reproduce**
https://xcp-ng.org/forum/topic/2804/yum-upgrade-8-0-to-8-1-vm-memory-error/

**Expected behavior**
No error, banner shoudl show that it is deprecated

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.

**Hard-/Software involved:**
.

**Additional context**
.

**Comment by cocoon** [comment]
Confirmed: 
commenting this line:
https://github.com/xcp-ng/xenadmin/blob/development/XenAdmin/TabPages/BallooningPage.cs#L468

removes the error but the "Details"-Link then does nothing.

So I think it would be better to provide an own DEPRECATION_URL or the previous one.

**Comment by schulz-alexander** [comment]
Hmm.. can you analyse to what that url should lead to? A webpage or some sort of data?

**Comment by cocoon** [comment]
I "think" it would be this:
https://docs.citrix.com/en-us/citrix-hypervisor/whats-new/removed-features.html

but I can confirm this with the other client.

Update: confirmed, this page opens.

**Comment by schulz-alexander** [comment]
I change the DEPRECATION_URL to https://github.com/xcp-ng/xcp/wiki/XCP-ng-8.1-Release-Notes
