### ISSUE TITLE
Pool Memory Tab: show memory in relation to each other

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#19]
Different amount of used server memory has the same size

![grafik](https://user-images.githubusercontent.com/5782951/38587631-74ed6152-3d22-11e8-9f7d-37d8637a25ca.png)

Idea (edited the above image): amount of used memory in relation to each other (should be a switchable option)

![grafik](https://user-images.githubusercontent.com/5782951/38588446-2cd0d350-3d26-11e8-9b0d-b0068e86cd7e.png)

**Comment by andrewhalley** [comment]
Looks cool.  Something to upstream?

**Comment by borzel** [comment]
Pull request is there! Close!

**Comment by olivierlambert** [comment]
Do not close the issue, it will be closed automatically if you refer in the PR description that it fixes this issue number, when the PR will be merged.

**Comment by borzel** [comment]
Ahh ohh... good to know
