### ISSUE TITLE
All of a sudden, XCP Center XCP-ng-Center-20.04.00.32 says user.config "Root element is missing."

### ISSUE THREAD

**Issue by jobsoftinc** [xcp-ng/xenadmin#191]
Windows 10 Enterprise with latest updates. Had a system crash, and XCP Center wouldn't start after that. Did DISM and SFC scans, used Revo to fully uninstall XCP Center, then loaded previous release (XCP-ng-Center-20.03.01.31), but same error. Revo'd again, and purged the Roaming profile folder as well. Installed XCP-ng-Center-20.04.00.32 again, same error. Revo'd again, removed Roaming profile folder, and installed 2019 version XCP-ng-Center-8.0.1.26 instead. Ran just fine! So, I upgraded it back to XCP-ng-Center-20.04.00.32, and again, the error. I had upgraded it to XCP-ng-Center-20.03.01.31 back in the middle of June, so it had run for 2-3 weeks just fine as well. Obviously, something's changed. Attached is the log file showing sessions from XCP-ng-Center-8.0.1.26 and the upgrade to XCP-ng-Center-20.04.00.32. Also attached is the current user.config for XCP-ng-Center-20.04.00.32.
[XCP-ng Center.log](https://github.com/xcp-ng/xenadmin/files/4885516/XCP-ng.Center.log)
[user.config.zip](https://github.com/xcp-ng/xenadmin/files/4885520/user.config.zip)

**Comment by HeMaN-NL** [comment]
Same as this problem?
Could Not Load Settings #187

this woraround?
https://github.com/xcp-ng/xenadmin/issues/187#issuecomment-652305363

> The error message is incorrect. It says "Revert changes to C:\Users\<username>\AppData\Roaming\XCP-ng\...\user.config" However, it turns out that the corrupt file is actually C:\Users\<username>\AppData\Local\XCP-ng\...\user.config. It consists of all zero bytes. When I deleted that file and ran XCP-ng Center 20.4.0.32 again, it did indeed create a valid default user.config file and loaded successfully.

**Comment by jobsoftinc** [comment]
Would seem so. FWIW, using same "corrupt" config (copied to the fresh install of 8.0.1.26), it worked. Then, upgraded to 20.04.00.32, copied in same "corrupt" config, got error. I can't see anything wrong with XML file. Unless it has a corrupted server entry which may be breaking its parsing. When I uninstall it with Revo, I do the "advanced" post-uninstall-script-run to scan registry and filesystem for leftovers (which are then deleted). Some other post suggested Roaming had become "read only" but any version of XCP test recreates all the Roaming folders/files just fine (logs included). Since it ran OK with the upgrade to 20.03.01.31 for several weeks before it all of a suddenly didn't anymore. this why I'm suspecting something with with the recent PC crash "recovery" for the disk volume hosting AppData. I had also just run it yesterday (before the crash) trying to add back in a recently reloaded XCP 8.1 server. Seems like it had some challenge with trying to remove the previous instance of that server in the the server list. So, it might've this might be purely coincidental with the PC crash/recovery itself. Thanks!

**Comment by jobsoftinc** [comment]
I can try that case's workaround, but in reading through it, it would seem that i've already tried a number of those steps. Aside from this, I figured some one in the know would know why such an error would manifest itself in the first place? If the user.config XML is intact, what other conditions would result in such a parse (or open/access?) error? I do believe that it is something"environmental" with respect to my Windows 10 Enterprise install/state, and not likely an actual error in the XCP Center code and/or the .Net XML assembly, unless, of course, said some other environmental condition is now causing the XML assembly to bomb out on a perfectly legit XML file parsing. I suppose I could search for others reporting errors in general with this XML parser class in general.

**Comment by cocoon** [comment]
@jobsoftinc Hi, thanks for the files.
But the log you provided is trying to read the user.config from AppData\Local, not roaming.
```AppData\Local\XCP-ng\XenCenterMain.exe_Url_zgy2ft4zhzkcejgr02qwwlngl4rqizyf\20.3.1.31\user.config```

I think you provided the AppData\Roaming one?

I would need a file that causes the error to see what happened to that file.

**Comment by Solarbotics** [comment]
I found I had to fix/replace the one in the \local as well as the \Roaming before it'd work again.
