### ISSUE TITLE
Importing *.xva-file hangs with error "Exception has been thrown by the target of an invocation."

### ISSUE THREAD

**Issue by EugeneFlash** [xcp-ng/xenadmin#192]
**Describe the bug**
Cannot import xva file by the XCP-NG Center

**To Reproduce**
1. Go to 'File -->Import'
2. Browse xva-file
3. Click "Open", click "Next", click "Next", click "Import"
4. There is a windows with the "Preparing to import VM" that hangs for about 32 minutes
5. After that - an error "Exception has been thrown by the target of an invocation."

**Expected behavior**
Imported VM

**Screenshots / Logfiles**
![import_error](https://user-images.githubusercontent.com/26535649/91562852-8bc2bf80-e946-11ea-855d-a437ff3bb74e.jpg)
[XCP-ng Center.log](https://github.com/xcp-ng/xenadmin/files/5142153/XCP-ng.Center.log)
[XCP-ng Center Audit Trail.log](https://github.com/xcp-ng/xenadmin/files/5142154/XCP-ng.Center.Audit.Trail.log)

**Hard-/Software involved:**
 - Hardware: HPE DL380 Gen10
 - Host XCP-ng Version: 8.1.0
 - Client XCP-ng Center Version: 20.04.00.32
 - Desktop OS: Windows 7 SP1 64bit

**Additional context**
As a workaround I copy xva-file into /tmp and run  xe vm-import filename=xoa_unified.xva and the vm is on the list.

**Comment by olivierlambert** [comment]
Does it work with Xen Orchestra?

**Comment by EugeneFlash** [comment]
Did not try. Can't check write now, maybe next week.

**Comment by EugeneFlash** [comment]
XOA works like a charm! But imported VM views like a template. I use "xe vm-param-set is-a-template=false uuid=<VM UUID>" for it.

**Comment by olivierlambert** [comment]
If you exported an XVA as a template, it's "normal" :+1: 

But yeah, it's better to go through XO anyway.

**Comment by bsodmike** [comment]
I'm having this same issue, will see if XOA can help.
