### ISSUE TITLE
Issues with "Server Status Report" => XCP-ng Insight Services => MyCitrix Login

### ISSUE THREAD

**Issue by siodor** [xcp-ng/xenadmin#193]
**Describe the bug**
I was having trouble with an XCP-ng host and wanted to remove all crash dumps. In the process I found a few issues:

**XCP-ng Insight Services => MyCitrix Login**

**To Reproduce**
1. In XCP-ng Center
2. Right-click on "$XCP-ng_host"
3. Choose "Remove Crash Dump Files"
![3_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152071-69d3ac00-ee22-11ea-8141-1a7fa2d54b96.png)

4. On the following dialogue click on "Server Status Report"
![4_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152459-fb431e00-ee22-11ea-9e64-60fd04c4c326.png)

5. Choose "$XCP-ng_host" to create report for
![5_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152109-75bf6e00-ee22-11ea-94fd-1dfcf86bb50c.png)

6. Choose what to include in this report
![6_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152148-81129980-ee22-11ea-81d8-7a4ac1c97fac.png)

7. Wait for it to collect information/files
![7_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152156-853eb700-ee22-11ea-800a-634ae65c524b.png)

8. There's MyCitrix login credentials asked for, but the service is "XCP-ng Insight Services"?
![8_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152240-a3a4b280-ee22-11ea-9e7e-c202d6923e5c.png)

**Expected behavior**
I want to enter "MyVates" credentials :smiley:

**Comment by M1st3r-E** [comment]
did you end up finding which creds to put? im trying to find this online

**Comment by olivierlambert** [comment]
Insight service is a service by Citrix/XenServer, so:
1. There's no such thing on Vates, if you need assistance, just open a ticket and you'll have a human person helping you/analyzing the logs (now you can gather all logs from Xen Orchestra UI/CLI/API)
2. I'm not sure Citrix or XS servers will accept a report from XCP-ng Center, but in case it does, then it's obviously linked to your Citrix account. Not sure how happy they will be to review logs from XCP-ng.

**Comment by schulz-alexander** [comment]
we will not work on that
