### ISSUE TITLE
Issues with "Server Status Report" => "XCP-ng Privacy Statement" => Missing?

### ISSUE THREAD

**Issue by siodor** [xcp-ng/xenadmin#194]
**Describe the bug**
I was having trouble with an XCP-ng host and wanted to remove all crash dumps. In the process I found a few issues:

**XCP-ng Privacy Statement => Missing?**

**To Reproduce**
1. In XCP-ng Center
2. Right-click on "$XCP-ng_host"
3. Choose "Remove Crash Dump Files"
![3_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152071-69d3ac00-ee22-11ea-8141-1a7fa2d54b96.png)

4. On the following dialogue click on "Server Status Report"
![4_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152459-fb431e00-ee22-11ea-9e64-60fd04c4c326.png)

5. Choose "$XCP-ng_host" to create report for
![5_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92152109-75bf6e00-ee22-11ea-94fd-1dfcf86bb50c.png)

6. Click in "XCP-ng Privacy Statement", there's an error because it can't open any browser, tried in Windows 10 Pro Version 2004 with standard browser set to:
- Firefox 80.0.1
- Edge 85.0.564.44 (new Chromium based one)
- Internet Explorer Version 11.450.19041.0, Updateversion 11.0.205
![7 2_XCP-ng Center - Wants to send report to Citrix](https://user-images.githubusercontent.com/38102740/92153796-19aa1900-ee25-11ea-8724-35c252e1b3ba.png)

**Expected behavior**
Something, presumably a browser, should open the "XCP-ng Privacy Statement".

**Comment by schulz-alexander** [comment]
we will not work on that
