### ISSUE TITLE
XCP-ng Center for XCP-ng 8.2

### ISSUE THREAD

**Issue by schulz-alexander** [xcp-ng/xenadmin#195]
* [x] setup build-environment (Visual Studio 2019)
* [x] build dotnet-packages
* [ ] build xenadmin upstream
* [ ] merge changes from upstream into xcp-ng-xenadmin
* [ ] build xcp-ng-center with branding
* [ ] pre-release for testers
* [ ] release for all :-)

**Comment by fachex** [comment]
Thank you for your hard work. I can't wait for this to work.

**Comment by stormi** [comment]
Hi. Will there be a new release in time for XCP-ng 8.2 (release in approximately 2 weeks)? If there weren't, I would need to update the landing HTML page to remove the link to https://github.com/xcp-ng/xenadmin/releases in order to avoid making beginner users download a release that doesn't support their host.

**Comment by sheo0147** [comment]
I’m waiting for the release of 8.2 support.
- What are you thinking about when will you release?
- Is there anything I can do to help you?

**Comment by cheese** [comment]
It is needed to connect to console of VMs. Is there any simpler software can connect to VM console?

**Comment by olivierlambert** [comment]
You can install XO even locally on your PC if you don't want to deploy it in a VM on your host :)

**Comment by aidanwardman** [comment]
Awaiting this release with anticipation! Any one know how i can downgrade 8.2 to 8.1 in the interim?

**Comment by axiom00** [comment]
> 
> 
> You can install XO even locally on your PC if you don't want to deploy it in a VM on your host :)

@olivierlambert Can you elaborate on this comment? I looked for documentation on XO local install but didn't find any. Thanks!

**Comment by olivierlambert** [comment]
Just follow the "from the sources" install on your local machine, that's it.

**Comment by prilly-dev** [comment]
What is this!? i cant find anything in the release note for XCP-NG 8,2 that xcp-ng Center is not available for this version or that the currently release xcp-ng center is not compatible with 8.2

This is just to darn lazy. xcp-ng 8.2 should not have been release before xcp-ng center is ready.

iam going back to xenserver, this is just to crazy

**Comment by biggen1684** [comment]
> What is this!? i cant find anything in the release note for XCP-NG 8,2 that xcp-ng Center is not available for this version or that the currently release xcp-ng center is not compatible with 8.2
> 
> This is just to darn lazy. xcp-ng 8.2 should not have been release before xcp-ng center is ready.
> 
> iam going back to xenserver, this is just to crazy

[redacted by stormi].  Go and build XO yourself for free and have everything you could possible need.

XCP-NG Center was never adopted by the xcp-ng team.  Its community supported and not officially supported at all.  I for one can't wait till its dead and gone and everyone is on XO to avoid confusion in the future.

**Comment by stormi** [comment]
Please remain respectful. I've edited your post.

**Comment by biggen1684** [comment]
Sorry.  People that act like spoiled brats deserved to be called out.

**Comment by prilly-dev** [comment]
> Sorry. People that act like spoiled brats deserved to be called out.

So here you are calling me spoiled!? 

The fact is that the xcp-ng team released a first version of center to lure in users from xenserver, and slowly without mentioning it forcing this users over to xo when they dont have much choice. Failing mentioning this vital information is done so even more users throw in their towel to use xo.

Still we se that xcp-ng center has the xcp-ng logos, it is hosted on their repositories and there is no easy way to find information that they intende to abandon center.

They are more interesting getting you over to xo then informing about this issues.

It was a planned cruel stunt performed by xcp-ng team where they want to increase financial benefit, it was known tonthe team that this problem existed but they keep their mouth shut about it, and as you see here thei are activly promoting xo as a solution. So the intention is pretty clear.

Dont call me spolied for calling out this marketing stunt from xcp-ng team.

**Comment by olivierlambert** [comment]
Okay I did some cleaning and the user will be banned. No need to feed the troll. Issue locked to let @borzel work in good conditions.

**Comment by cocoon** [comment]
To reduce the pressure a bit I thought I will jump in to help out with an interim unofficial build.

Feel free to try it, most fixes are includes, but there may be missing some.
But it might help the one or other:

https://github.com/cocoon/xenadmin/releases/

**Comment by schulz-alexander** [comment]
there is now a "quick" release for XCP-ng 8.2 compatibility: XCP-ng Center 20.04.01: https://github.com/xcp-ng/xenadmin/releases/tag/v20.04.01.33

**Comment by stormi** [comment]
Thanks borzel and thank you cocoon, I think some users will be happy :)

**Comment by stormi** [comment]
Now we need to update https://xcp-ng.org/docs/release-8-2.html#status-of-xcp-ng-center

I'll do it when I can, don't hesitate to beat me to it or to remind me if I forget.

**Comment by olivierlambert** [comment]
On it :+1:

**Comment by olivierlambert** [comment]
Done and doc refreshed :+1:
