### ISSUE TITLE
xcp-ng center add server version error

### ISSUE THREAD

**Issue by holtdw** [xcp-ng/xenadmin#196]
successfully installed xcp-ng 8.2, installed xcp-ng center 20.04.0   added server and get the following error
![XCP error](https://user-images.githubusercontent.com/59939038/96892160-5ecaee80-1457-11eb-8bd9-2233b41714ce.png)

what am I missing here.   version xcp-ng 8.2 compatibility problem?

**Comment by splastunov** [comment]
Hello!

Same problem here.
XCP-ng 8.2 released yesterday, but there is no compatible Center for windows yet....

Are there some plans to release new version of xcp-ng Center?

**Comment by olivierlambert** [comment]
Hi there!

XCP-ng Center is only community maintained and not officially supported client. Until the current community maintainer can have time, I suppose help from others is welcome. See https://github.com/xcp-ng/xenadmin/issues/195

See the list of multiple clients you can use: https://xcp-ng.org/docs/management.html
