### ISSUE TITLE
couldn't save config file

### ISSUE THREAD

**Issue by PappBence** [xcp-ng/xenadmin#197]
I get this error when xenadmin closed, but the settings are saved to the file.
I deleted it, but still get error message. File permissions is OK.
Version: 20.04

![xenadmin](https://user-images.githubusercontent.com/425259/97730232-e4900f00-1ad3-11eb-9f4c-3d233824d281.png)

**Comment by gn-ro** [comment]
I have the same error. I have deleted the folder from AppData, reinstalled, repaired the installation, all to no avail. It will not start. Older version works fine.
![image](https://user-images.githubusercontent.com/61818482/100384409-c82ab800-3028-11eb-94a9-3d8668946d98.png)


I think this is the same with [https://github.com/xcp-ng/xenadmin/issues/187](https://github.com/xcp-ng/xenadmin/issues/187)

**Comment by schulz-alexander** [comment]
we will not work on that
