### ISSUE TITLE
XCP-ng not detecting xe-guest-utilities on new VMs

### ISSUE THREAD

**Issue by philipwilk** [xcp-ng/xenadmin#199]
Usually, under VM general properties under general, XCP-ng shows if guest utils are installed on the VM next to _Virtualization state_. This seems to be working fine on existing VMs, but on newly created VMs XCP-ng thinks that they are not installed when they are.

**Steps to reproduce:**
1. Create a new VM
2. Install as usual
3. Install `xe-guest-utilities` on the VM
4. Check the "virtualization state" in XCP-ng

**Expected behaviour:**
When the utilities are installed, it should be shown next at virtualisation state along with a version number.
Intended:
![image](https://user-images.githubusercontent.com/50517631/101241153-9c27ca80-36eb-11eb-853e-8015a4040a74.png)
Actual:
![image](https://user-images.githubusercontent.com/50517631/101241138-81edec80-36eb-11eb-8de3-f95a9635dec1.png)

**Hard-/Software involved:**
 - VM details: Ubuntu Server Focal Fossa
 - Host XCP-ng Version: 8.1
 - Client XCP-ng Center Version: 20.04.00
 - Desktop OS: Windows 10 20H2 // 19042.630

**Additional Context:**
On one of my other VMs that I upgraded to Focal Fossa and then upgraded the guest-utils, they are detected fine; only new VMs are being treated like this.

**Comment by stormi** [comment]
I'm not sure whether this is really related to XCP-ng Center. 

In order to be sure: what steps did you follow to install the guest utilities?

Is the `xe-linux-distribution` service running in the VM? Is the `xe-daemon` binary running?

**Comment by philipwilk** [comment]
> I'm not sure whether this is really related to XCP-ng Center. 
> 
> In order to be sure: what steps did you follow to install the guest utilities?
> 
> Is the `xe-linux-distribution` service running in the VM? Is the `xe-daemon` binary running?

I've done what i usually do in my VMs (which don't have the issue) of mounting the virtual disc and running /Linux/install.sh or whatever it is

**Comment by stormi** [comment]
Sorry about the delay. Are you still stuck with this guest utilities issue?

**Comment by philipwilk** [comment]
I just checked on a different installation of XCP-ng Center and yes I'm still experiencing this issue.

**Comment by stormi** [comment]
I just noticed that you didn't answer to this question: `Is the xe-linux-distribution service running in the VM? Is the xe-daemon binary running?`. And if it's not running: is the service activated? If it is, what do the system logs say about its failure (not logs from XCP-ng Center, logs from the linux system itself)?

**Comment by philipwilk** [comment]
Here is what comes up on the VM with working xe-utils detection:
![image](https://user-images.githubusercontent.com/50517631/104059235-e3264580-51ec-11eb-9b7a-1af0b9c7dece.png)
and here is what comes up with the one that isn't visible in XCP-ng center:
![image](https://user-images.githubusercontent.com/50517631/104059305-07822200-51ed-11eb-824d-7b58d7555b8c.png)

I don't know how important this is exactly, but XCP-ng center can tell that the VM is "I/O optimized" but not that the management agent is installed. 
I have also recently installed the management agent on a windows 10 VM and can confirm that the detection with a windows VM works fine.

**Comment by stormi** [comment]
I/O is always optimized on linux, so no worry about that. Apparently the service is running, so I don't know why it's not detected as such.
