### ISSUE TITLE
What about the help files (*.chm)

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#20]
they're not available as source, just compiled as *.chm files

- [ ] can we use the original files for branding?
- [ ] try to decode with something like this [CHM Decoder](https://alternativeto.net/software/chm-decoder/) - Download [here](gridinsoft.com/download.php?chm)

**Comment by stormi** [comment]
We should open an issue upstream about the lack of sources for the help files.

**Comment by borzel** [comment]
Lets see what they say: https://bugs.xenserver.org/browse/XSO-937

**Comment by borzel** [comment]
There is an answer... no surprises so far...

Just for fun I read the license for the online help... you are not allowed anything. So I think we have two options:
* no help
* someone writes it

**Comment by stormi** [comment]
There's also: 
* insist on the publication of the source for the help files because they've been published as free software... But it depends on the exact license(s) for XenCenter
* extract them from the .chm files (unless the license states that we can't reuse them).

**Comment by schulz-alexander** [comment]
we will not work on that

**Comment by Harmanxcp2025** [comment]
Hello Team,

when i starting import the vm from vCenter to xcp-ng, but multiple time 
failed. Please advice
