### ISSUE TITLE
Compatible version location missing ?

### ISSUE THREAD

**Issue by Grip3n** [xcp-ng/xenadmin#200]
Good day

I upgraded to xcp-ng-8.2.0  from 8.1.0
using XCP-ng Center version 20.04.00 (build 20.04.00.32)
got the following message (see attached)
The Location is empty ?

Not sure if this is a bug or intentional seeing still working on a compatible version ?
if intentional should it not point to the releases tree ?

[![XCPNG.jpg](https://i.postimg.cc/T1w2Xb60/XCPNG.jpg)](https://postimg.cc/G8WnFH9T)

**Comment by olivierlambert** [comment]
Closing as dup of https://github.com/xcp-ng/xenadmin/issues/195

edit: adding some context from our Release notes: https://xcp-ng.org/docs/release-8-2.html#misc
