### ISSUE TITLE
Error import VM from OVF to VMware Workstation

### ISSUE THREAD

**Issue by mshalmanov** [xcp-ng/xenadmin#202]
Hello.
I can export VM to OVF file.

![изображение](https://user-images.githubusercontent.com/4174493/114039773-d75a2600-98a4-11eb-9797-b3fbcac55b9d.png)

When i can import my OVF file, i have error 

Failed to open virtual machine: Line 2: Unsupported section 'StartupSection' (Startup Options).

Line 2: Unsupported element 'VirtualSystemOtherConfigurationData'.

Line 2: Unsupported element 'VirtualSystemOtherConfigurationData'.

Line 2: Unsupported element 'VirtualSystemOtherConfigurationData'.

Line 2: Unsupported element 'VirtualSystemOtherConfigurationData'.

Line 2: Unsupported element 'VirtualSystemOtherConfigurationData'.

![изображение](https://user-images.githubusercontent.com/4174493/114044501-1ab69380-98a9-11eb-906e-432e01bb624f.png)

How i can fix this errors and import my VM from OVF file?

Please i need help.

**Comment by schulz-alexander** [comment]
tried with XCP-ng Center Nighlty Build 30 (to be releases) - not problems here
