### ISSUE TITLE
New *.2 XCP-NG Install

### ISSUE THREAD

**Issue by jimthedj65** [xcp-ng/xenadmin#203]
**Describe the bug**
Fresh install, trying to do yum update / upgrade and produces an error that the base repo is not available.

**To Reproduce**
1. Install on bare metal
2. ssh in as root 
3. try to run an yum update / upgrade
yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Excluding mirror: updates.xcp-ng.org
 * xcp-ng-base: mirrors.xcp-ng.org
Excluding mirror: updates.xcp-ng.org
 * xcp-ng-updates: mirrors.xcp-ng.org
http://mirrors.xcp-ng.org/8/8.2/base/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.xcp-ng.org; Unknown error"
Trying other mirror.
http://mirrors.xcp-ng.org/8/8.2/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.xcp-ng.org; Unknown error"
Trying other mirror.

 One of the configured repositories failed (XCP-ng Updates Repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=xcp-ng-updates ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable xcp-ng-updates
        or
            subscription-manager repos --disable=xcp-ng-updates

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=xcp-ng-updates.skip_if_unavailable=true

failure: repodata/repomd.xml from xcp-ng-updates: [Errno 256] No more mirrors to try.
http://mirrors.xcp-ng.org/8/8.2/updates/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.xcp-ng.org; Unknown error"

**Expected behavior**
should do the upgrade or update from the base mirror repo

**Hard-/Software involved:**
 System details
OS Other Customer Installed OS 1.0.0 (xcp-ng 8.2)
Security Device SuperMicro AOM-TPM-9671H
Remote Mgmt Card Aspeed AST2500 - Onboard
RAM 12x 32GB Samsung 32GB DDR4 2Rx4Modify
Processor 2x 2.4GHz Intel Xeon-Cascade-Lake (8260-PLATINUM)Modify
Power Supply 2x SuperMicro PWS-1K02A-1R
Network Card SuperMicro AOC-2UR66-I4XTF
Motherboard SuperMicro X11DPU+_R1.10View details
Drive Controller LSI 9461-16iView detailsModify
Battery Broadcom 49571-22
Backplane SuperMicro BPN-SAS3-826EL1-N4

**Additional context**
looking for assistance on the yum update / upgrade error

**Comment by olivierlambert** [comment]
Seems like a DNS issue. Please check your DNS settings :)

**Comment by jimthedj65** [comment]
Hi Olivier I check DNS and sure enough the settings were blank, that's all fixed, and when I go to XOA deploy I am getting the following error

Unexpected token < in JSON at position 0

**Comment by olivierlambert** [comment]
Please create a thread in our community forum, this repo isn't the place for that issue :)

https://xcp-ng.org/forum/

**Comment by jimthedj65** [comment]
ok thank you
