### ISSUE TITLE
Dynamic memory control isn't deprecated on XCP-ng

### ISSUE THREAD

**Issue by BasixKOR** [xcp-ng/xenadmin#208]
**Describe the bug**
XCP-ng Center reports that DMC has been deprecated since 8.1, but [the dev has noted that they will keep DMC support.](https://xcp-ng.org/forum/topic/2947/dynamic-memory-deprecated?_=1619533083324)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a server running XCP-ng 8.1 or above.
2. Click on any VM with DMC set up.
3. Click the memory tab.
4. See the warning.

**Expected behaviour**
A warning shouldn't be shown.

**Screenshots / Logfiles**

**Hard-/Software involved:**
Likely irrelevant.

**Additional context**

**Comment by schulz-alexander** [comment]
Tested with Nightly Build 30 (to be released), it should work

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/85a7af6c-eb0c-46d7-831c-2220253012d5)

**Comment by schulz-alexander** [comment]
https://github.com/xcp-ng/xenadmin/releases/tag/v.99.99.99.30
