### ISSUE TITLE
encrypting a virtual machine disk

### ISSUE THREAD

**Issue by bayramaslan** [xcp-ng/xenadmin#209]
Hi, 
i want ask that is is possible encrypting a virtual machine disk via xcp-ng center ? It seems possible by virtualbox like in photo:

![Screenshot from 2022-04-22 11-17-31](https://user-images.githubusercontent.com/104194437/164647814-fa4ee17d-75c7-42af-8041-f1621047b00f.png)
.

**Comment by olivierlambert** [comment]
Hi,

1. Virtualbox is a complete different platform than XCP-ng
2. There's no support in XCP-ng for VM disk encryption right now (it might come in the future)
3. XCP-ng Center is only community maintained, I would suggest to use another client to manage your hosts :)
