### ISSUE TITLE
Screen-Scaling breaks tree-view

### ISSUE THREAD

**Issue by RHuehne** [xcp-ng/xenadmin#210]
**Describe the bug**
When Windows is not used in native resolution, but scaled XCP-NG Center tree view pane does not stick to it's outer frame

**To Reproduce**
1. Set Windows Custom Scaling to 125%  (seen on different Machines, especially when using RDP)
2. Start XCP-NG Center

**Expected behavior**
The tree-view in the left pane uses the whole pane.
![xcp-bug](https://user-images.githubusercontent.com/13745200/165064684-e9130d06-8553-4466-b51e-e129d0e4024e.png)

**Comment by olivierlambert** [comment]
Since this repo is only community maintained without a lot of contributions lately, you might have better chances to report this upstream directly (here: https://github.com/xenserver/xenadmin)

**Comment by cocoon** [comment]
Hi, yes scaling often causes problems, but currently I was unable to reproduce it on my machine (Win11 and Server 2016), tried 125%, 150% and it was OK here.

Can you tell more about the system (Windows, GPU + Driver, ...)?

**Comment by RHuehne** [comment]
> Since this repo is only community maintained without a lot of contributions lately, you might have better chances to report this upstream directly (here: https://github.com/xenserver/xenadmin)

Hi There! 

Thanks! Done: https://github.com/xenserver/xenadmin/issues/2995

Cheers

**Comment by stormi** [comment]
@RHuehne upstream's product is not XCP-ng Center so you should first reproduce with theirs (XenCenter), not ask them about bugs in XCP-ng Center but about bugs in XenCenter, and make sure you test the latest release (XCP-ng Center has not been updated in a while).

**Comment by RHuehne** [comment]
sorry... I don't get that?
Official Xencenter cannot connect to XCP-NG Hosts... or did this change? 

UPDATE: ... ok... I don't need a Server... :) -> Updated Request for XenServer

**Comment by schulz-alexander** [comment]
I could also not reproduce your issue.

local screen with 200% scaling

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/a5232c35-e4c4-4e2c-a5c0-1cc18fd93410)

**Comment by schulz-alexander** [comment]
https://github.com/xcp-ng/xenadmin/releases/tag/v.99.99.99.30

please test and reopen when needed
