### ISSUE TITLE
XCP-ng Centre 20.04.01 - VM Autostart on Server Boot not working

### ISSUE THREAD

**Issue by MichaelCropper** [xcp-ng/xenadmin#211]
Detailed steps to reproduce outlined here: https://xcp-ng.org/forum/topic/6335/xcp-ng-centre-20-04-01-vm-autostart-on-server-boot-not-working

**Comment by themodernpk** [comment]
Just wanted to confirm that this issue does exist.

**Comment by timemaster5** [comment]
yep, me too

**Comment by K0ntrast** [comment]
Me three.

**Comment by schulz-alexander** [comment]
I tried to add the poolwide-autoboot setting, but the save-logic in Center is not very transparent to me, so I was not able to save the change of the pool other_config.

But I added an information on host/pool level:

![grafik](https://github.com/xcp-ng/xenadmin/assets/5782951/dfa63d0b-a379-47f6-8a32-9d141b7614fa)

**Comment by schulz-alexander** [comment]
https://github.com/xcp-ng/xenadmin/releases/tag/v.99.99.99.30
