### ISSUE TITLE
xcp-ng 8.3 alpha reports Xcp-ng Centre is too old.

### ISSUE THREAD

**Issue by lkernan** [xcp-ng/xenadmin#213]
**Describe the bug**
The version of Xcp-ng Centre is considered too old and unable to connect to Xcp-ng 8.3 public alpha.

**To Reproduce**
1. Install Xcp-ng 8.3 public alpha
2. Try to connect with the latest build of Xcp-ng Centre

**Expected behavior**
Xcp-ng Centre would be expected to be able to connect.

**Comment by diegogyn** [comment]
The same thing with me, the Alpha 2 version does not connect. It would be good to connect already to do the tests, even if it is not the default XCP-NG client here we use Center instead of XOA.

**Comment by jailbird777** [comment]
It would be nice if there was a doc on how to transform XenCenter -> XCP-ng Center, so that people in the community can help. Maybe there is one that I just can't find?

**Comment by seanmcg182** [comment]
Issue still unresolved 8.3 Beta 1

**Comment by schulz-alexander** [comment]
Hello, i put together a new version with the latest changes from https://github.com/xenserver/xenadmin from December 2023.

It is basically working with XCP-ng 8.3 beta.

It's a DEBUG-Developer build, unpack it and just run.

**It is not finished - please use only in Test- and Delevopment-Environments!**

It is not correctly branded to XCP-ng!

[XCP-ng Center 2023.12.DEV.DEBUG.zip](https://github.com/xcp-ng/xenadmin/files/13798926/XCP-ng.Center.2023.12.DEV.DEBUG.zip)

Please give your feedback!

I hope to publish a new release (XCP-ng 2023.12) very soon.

**Comment by seanmcg182** [comment]
> Hello, i put together a new version with the latest changes from https://github.com/xenserver/xenadmin from December 2023.
> 
> It is basically working with XCP-ng 8.3 beta.
> 
> It's a DEBUG-Developer build, unpack it and just run.
> 
> **It is not finished - please use only in Test- and Delevopment-Environments!**
> 
> It is not correctly branded to XCP-ng!
> 
> [XCP-ng Center 2023.12.DEV.DEBUG.zip](https://github.com/xcp-ng/xenadmin/files/13798926/XCP-ng.Center.2023.12.DEV.DEBUG.zip)
> 
> Please give your feedback!
> 
> I hope to publish a new release (XCP-ng 2023.12) very soon.

Confirmed capability to still manage vApps. 
Completely Shocked its not a feature in XO... Last thing I want to do is manage my start order/timings in CLI.

You're the best Borzel!

**Comment by cocoon** [comment]
Hey welcome back Borzel!

I also worked on automated building and branding the new one and have a slightly themed one compiled today, too. 
I totally scripted the automated branding from scratch.
Not everything removed or tested also, but here this is it.

![2023-12-31-splash](https://github.com/xcp-ng/xenadmin/assets/1071741/3c94e2d0-5c2f-4b4c-8fbb-f302dbd4648b)
![2023-12-31-window](https://github.com/xcp-ng/xenadmin/assets/1071741/85246547-f788-4b31-93e5-ccf992a1be5d)

[XCP-NG-Center-2023-Release.zip](https://github.com/xcp-ng/xenadmin/files/13800584/XCP-NG-Center-2023-Release.zip)


edit: tried to find best matching replacements for URLs but "Context help" is not working correct for now for example..
![2023-12-31-resx](https://github.com/xcp-ng/xenadmin/assets/1071741/6daeca2d-968d-4983-ad20-fd3680c93fcf)

**Comment by schulz-alexander** [comment]
I released a nightly build for testing: https://github.com/xcp-ng/xenadmin/releases/tag/v99.99.99.29
