### ISSUE TITLE
Open "XCP-ng Center.exe" with parameters/arguments

### ISSUE THREAD

**Issue by TerAnYu** [xcp-ng/xenadmin#214]
Hello!
Please tell me, is it possible to run "XCP-ng Center.exe" with connection address parameters/arguments and login/password?
If yes, then please indicate how to do this (I couldn’t find it in the documentation).
For example:
```
XCP-ng Center.exe -XcpServerAddress=10.0.0.1 -XcpLogin=user -XcpPassword=passwd
```

**Comment by cocoon** [comment]
Try it with:

`XenCenterMain.exe connect Hostname Username Password`
