### ISSUE TITLE
Simplify building process

### ISSUE THREAD

**Issue by schulz-alexander** [xcp-ng/xenadmin#215]
Citrix / Cloud Software Group, Inc. stated in the readme.md file at https://github.com/xenserver/xenadmin:

"**Please note that as of December 2023 this copy of the XenCenter repository is considered archived. As such it will not reflect the latest state of XenCenter development, and any pull requests will not be reviewed/merged.**"

I think, XenCenter is basically closed source now. So we don't get any changes in future from this repository.
So I would make some changes to the XCP-ng Center to make the development and building more easy:

- [x] Remove the brandingsystem, because we don't need to deliver XCP-ng Center under other brands. Benefit: Clean build from sources has the XCP-ng look without additionaly branding steps outside Visual Studio.
- [x] Remove unused code.
- [x] Remove reporting features.
- [x] Simplify the build process (checkout, open in VS, build).
- [x] Have a clean foundation for future maintenance and development.

@cocoon and others: What do you think?

**Comment by olivierlambert** [comment]
Maybe it's time to focus on XO Lite since it will be available by default in 8.3 and the current versions starts to be really usable. We'll be happy to have external contributions :)

**Comment by schulz-alexander** [comment]
@olivierlambert of course ;-)
But i'm more used to C# development, so I spend my time here on XCP-ng Center

@cocoon I released https://github.com/xcp-ng/xenadmin/releases/tag/v99.99.99.29, it originates from a new branch "https://github.com/xcp-ng/xenadmin/tree/brand_to_xcp-ng" where I branded all the source to XCP-ng and got rid of the annoying branding system.

Buidling a release is now simply as:

- open the source
- change the version values in CommonAssemblyInfo.cs
- change to release build
- build
- package as we want

**Comment by olivierlambert** [comment]
@borzel no worries we can brief you into XO Lite. I think it will be more efficient to guide all our resources to something that has a real future. I mean, it's fine to continue to make build to be compatible, but at some point, it's a dead end. Let me know when/if you are interested to be briefed on XO Lite.

Also, we might need some help on rebuilding the PV tools, assistance welcome too :) Nice to have you back!

**Comment by cocoon** [comment]
@Borzel Yes what a great announcement to stop public access to the sources ... just when I had my fully automated system ready ^^
Now it makes seance to have everything already branded as we might not get any new sources, so yes, is totally OK.

@olivierlambert I am also still a user that uses both, XO and Center as both just have their benefits and the same for me, c# is much more my world then the javascript one.
Also Center has still the benefit to be quick, intuitive, responsive and have all pools or single servers in one client without an extra VM, easy to add custom plugins, where Light is just on every single node/cluster ... afaik at least now you don't need to know what the current master is to log in, have not tested it in the last months, too much other stuff to do :)

(and of course the famous tree view ..., I know XO 6 should have it somewhen)

**Comment by olivierlambert** [comment]
@cocoon I'm talking about XO Lite, which purpose is exactly to replace XenCenter entirely (unlike XO which requires a dedicated VM to run).

XO Lite already provides a tree view, is bundled right into 8.3 (nothing to install) and also works offline.

See a live screenshot I made on a machine at home:

![image](https://github.com/xcp-ng/xenadmin/assets/1241401/2fef4fbd-a0fc-4fec-9a1d-e1312620c7f5)

That's why to me it's better to focus on the replacing bit instead of maintaining multiple tools. But it's just a suggestion :)

**Comment by cocoon** [comment]
Yes Looks nice 👍

So XO Lite will be able to manage multiple Servers,Pools,Clusters in one Interface Like Center and vApps ... ?

**Comment by olivierlambert** [comment]
XO Lite perimeter is per pool, not meant to be a centralized solution (and that's when XO makes sense). Otherwise, in terms of features, it's meant to replace XenCenter, so yeah.

1. Bootstrap your host/manage them locally: XO Lite
2. Centralized mgmt and potentially more (backup and such): XOA

Obviously, more contributions means feature parity sooner.

**Comment by schulz-alexander** [comment]
@cocoon and @olivierlambert can we move this conversation to the forum? this ticket is not about xo-lite ;-)

**Comment by schulz-alexander** [comment]
merged to development branch
