### ISSUE TITLE
xcp-ng 8.2 reports Xcp-ng Centre is too old

### ISSUE THREAD

**Issue by schulz-alexander** [xcp-ng/xenadmin#216]
from https://xcp-ng.org/forum/post/69039

![8ba4c74f-1b8d-46e5-be81-ad43dc969075-image](https://github.com/xcp-ng/xenadmin/assets/5782951/9bd47180-425b-4a68-970e-a349d849d47c)

Solution: correct API-Version enum!

**Comment by rvreugde** [comment]
Does not work with version 8.3
![image](https://github.com/xcp-ng/xenadmin/assets/38208623/30275911-3956-4264-8274-319f18e61732)
