### ISSUE TITLE
Automate nightly builds

### ISSUE THREAD

**Issue by mf** [xcp-ng/xenadmin#218]
Would it be possible to introduce some CI/CD for the nightly builds? I would love to test the new features, but the fix for 8.2 detection is was not included in the compiled version

**Comment by schulz-alexander** [comment]
latest build is here: https://github.com/xcp-ng/xenadmin/releases/tag/v.99.99.99.30

there are no plans nor capacity to automate things, as XCP-ng Center development will be stopped in favor of XO-Lite
