### ISSUE TITLE
New Name for "XenCenter"

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#22]
Which would we all like?

1. xenadmin
2. XCP-Center
3. XCPCenter
4. XCP-ng Console **<-- current work name**
5. XCP-ng Control
6. XenControl
7. Rocket Remote Control
8. Missile Remote Control
9. XenRocket

Other Ideas?

I'm also fine to stick with "XCP-ng Console" :-)

**Comment by olivierlambert** [comment]
We should avoid any "Xen" word as possible. "XCP-ng something" is a good start IMHO.

**Comment by necouchman** [comment]
> We should avoid any "Xen" word as possible.

Any particular reason?  Xen itself is open-source and used it other places (XenOrchestra, for example :-) - is there some reason the lawyers are saying we need to avoid that?

I'd vote for something like XCP-ng Center or XCP-ng Console - I don't think there's any reason to stray too far from the current name of the software.

**Comment by olivierlambert** [comment]
Because Citrix asked me explicitly to avoid playing with their trademarks.

**Comment by necouchman** [comment]
> Because Citrix asked me explicitly to avoid playing with their trademarks.

That's fair.  Interesting that they're targeting you/this project in particular, when there are many other open source projects out there that make use of the "Xen" name.  Oh well, we shall do our best to make sure we don't make them any more angry than they must already be at us :-).

**Comment by olivierlambert** [comment]
That's the objective, yes :wink:

**Comment by gangsterrapper22** [comment]
In my opinion XCP-ng Center or XCP-ng Console would be best name for it.

**Comment by Danp2** [comment]
XCP-ng Manager

**Comment by InterXellar** [comment]
I like XCPCenter i would stick with that one 👍

**Comment by borzel** [comment]
Important to know: https://www.citrix.com/content/dam/citrix/en_us/documents/about/citrix-trademark-list.pdf

**Comment by JoCord** [comment]
I like XCP-ngCenter, as XCP-ng is the new name for this project. On the homepage of the project I also saw XCP-NG, but I like the small letters :)

With XCP-ngConsole I always think of the command line console inside the Center application.

**Comment by PedroMesquita** [comment]
I like XCPCenter!

**Comment by xiscoj** [comment]
I likde XCPCenter too or something but not with ng, don't like in the name

**Comment by gangsterrapper22** [comment]
I think we should make an poll wit a few names and decide after this, which we should take. I think that is the easiest way, how to find out which name should be taken.

**Comment by Danp2** [comment]
Maybe we should drop the "CP" and call it XNG Center.

**Comment by borzel** [comment]
XenCenter -> XngCenter ?

**Comment by thtanner** [comment]
"Console" seems to usually signify command-line, even though that's not always the case. I'd personally vote for:

#1: XCP-ng Manager
#2: XCP-ng Center

**Comment by borzel** [comment]
If think, we can leave the console alone and focus on "Center" or "Manager".

**Comment by borzel** [comment]
Can someone create a poll? Shootout between "XCP-ng Manager" and "XCP-ng Center"

**Comment by borzel** [comment]
Vote here: http://www.easypolls.net/poll.html?p=5ad140a7e4b0f7307b174caa

**Comment by borzel** [comment]
Vote is over!
![grafik](https://user-images.githubusercontent.com/5782951/38772754-becd617c-403e-11e8-9134-22d43d48a7ed.png)

The name is "XCP-ng Center"
