### ISSUE TITLE
Error Loading Settings

### ISSUE THREAD

**Issue by vajra108** [xcp-ng/xenadmin#224]
I've been having this error "Could Not Load Settings" saying my saved settings appears to be corrupt. I can open the user.config document without an issue. Already uninstalled and reinstalled. Upon reinstalling, it worked. After closing, it won't open again with this error.
Also tried to delete the file, error keeps showing up even after deleting, and the address for the config file is correct in the image.

![Print Screen 2024-02-20 150329](https://github.com/xcp-ng/xenadmin/assets/125151065/def10761-14a9-4e04-addc-6a50d4c690ec)

**Comment by michael-manley** [comment]
Since I am redesigning the whole settings system in the final version, will close as Wontfix
