### ISSUE TITLE
XenCenter Version that is compatible with 8.2.1 and 8.3-beta

### ISSUE THREAD

**Issue by RHuehne** [xcp-ng/xenadmin#227]
I recently downloaded a 8.3 compatible version of XenCenter. That is working fine for connecting to the host equipped with 8.3-beta. When I try to connect to a 8.2 Host, I get the following error:

![image](https://github.com/xcp-ng/xenadmin/assets/13745200/b682a10b-13d4-4ae4-9353-17b2170ff315)

Which release can be used to connect to both XCP-NG versions and will allow me to Migrate a VM to the new Host?

As under "about" there is no version noted, I provide the filename I downloaded: XCP-ng.Center.2023.12.DEV.DEBUG

Many thanks,
Regards, Rainer

**Comment by RHuehne** [comment]
Anyone?

**Comment by cocoon** [comment]
Connection is working fine for me with:
https://github.com/xcp-ng/xenadmin/issues/213#issuecomment-1872827898
https://github.com/xcp-ng/xenadmin/files/13800584/XCP-NG-Center-2023-Release.zip

Does this one work for you?
I cannot say something about migration, but connecting to 8.2 and 8.3 beta pools is working for me.

**Comment by RHuehne** [comment]
Hi There, 

Thanks, looks good indeed!

Cheers,
