### ISSUE TITLE
XCP-ng Center hangs when try to enter maintenance mode

### ISSUE THREAD

**Issue by shepard1532** [xcp-ng/xenadmin#229]
Hi! I'ts my first issue report so be patient :)
I've got an issue when trying to put a Host into maintenance mode.
As soon the action is selected, the pending task hungs in xcp-ng center.

The xe task-list shows no pending task in xapi. It seems that the requested action
is not reaching actually the xapi.

In XCP-ng Center the task cannot be aborted. The process must be killed within Taskmanager.
After starting XCP-ng Center again, the host is still in normal function mode.

I've reproduces this with three more host lab machines.

For XCP-ng there was the actual LTS version in place (8.2 with all updates done)

I hope it is useful :)

Thanks Michael for taking over this great tool!

Have a nice day.

**Comment by SonGokuSSJ** [comment]
I installed an XCP-NG cluster with XCP-NG 8.2.1 last week and updated it and used XCP-NG v.99.99.99.30 (the last nightly build from January 12th) and was able to enter maintenance mode without problems. So if you did not try v.99.99.99.30, I suggest trying that as it has some bug fixes.

**Comment by shepard1532** [comment]
Thanks for your Answer. I will try that. Until now i was sticky to the "stable" version of xcp-nc center.

**Comment by michael-manley** [comment]
Yeah, I also cant reproduce this in later vNext builds (I recommend these as this will be the latest atm, I think ill plan a release around when 8.3 comes to RTW)
