### ISSUE TITLE
Linux/Mono Prototype

### ISSUE THREAD

**Issue by necouchman** [xcp-ng/xenadmin#23]
This is kind of a wish-list sort of item, and would probably take considerable effort, but it would be really nice to make XenCenter cross-platform capable.  I'm not sure if the DotNet components that it relies upon are available in the DotNet Core released for Linux and MacOS, which might make it easier.  If not, those components could be swapped out with something else, use a cross-platform GUI framework (QT comes to mind), etc., so that it can be compiled and run on Windows, Mac, and Linux.

Of course, none of this is to take away from the great work @olivierlambert is doing on XenOrchestra - having a Web UI is definitely preferable to a thick client like XenCenter, but sometimes for initial configuration of a cluster from scratch and some of the other one-time items it is nice to have the XenCenter GUI.  I just don't like to be tied to Windows for that.

**Comment by borzel** [comment]
Me too!

But this is a BIG item and for long term.

**Comment by necouchman** [comment]
> But this is a BIG item and for long term.

Yes, definitely - I just wanted to go ahead and get it on the list.  Maybe someone out there will see it, fork the repo, and start working on it :-).

**Comment by gangsterrapper22** [comment]
An Java XenCenter would be nice, because Java runs on the most platform and then you have only to compile one release and not per platform, but I thnk then we have to from scratch to make this possible.

**Comment by olivierlambert** [comment]
BTW @necouchman you can install Xen Orchestra on your computer, Windows/Mac or Linux. XOA is in a VM for the sake of easy deploy, but you can install it whenever you need :wink:

**Comment by necouchman** [comment]
> BTW @necouchman you can install Xen Orchestra on your computer, Windows/Mac or Linux.

Good to know, thanks!

**Comment by borzel** [comment]
Some reading material: https://github.com/xenserver/xenadmin/issues/3 Make XenCenter compile / run with mono

**Comment by borzel** [comment]
I did some test on Ubuntu 16.04 with MonoDelevop. I got it to the state where i can compile an exe.
But it throws exceptions after the first couple of initialisations.

![grafik](https://user-images.githubusercontent.com/5782951/39600685-d68acc38-4f1f-11e8-9f05-6c362d6e95dc.png)

**Comment by borzel** [comment]
after converting all png files in folder `/XenAdmin/Images` the ressouce file generation went trough and i could see the first paintings of the main "window" :-)

![grafik](https://user-images.githubusercontent.com/5782951/39605100-4a98cc4c-4f2f-11e8-97c7-202ea17fbccd.png)

**Comment by borzel** [comment]
It's not pretty and not stable, but first connection is made ;-)

![grafik](https://user-images.githubusercontent.com/5782951/39607654-6d016822-4f3c-11e8-8a52-ad4c3b3f8aee.png)

**Comment by eangulus** [comment]
I would also like a cross-platform XenCenter, but (and I know that this crosses over with XenOrchestra) but how about a XenCenter that will work remotely where I only have to forward some ports thru the router firewall. Citrix version never allowed XenCenter unless on the same network.

**Comment by olivierlambert** [comment]
The difference is Xen Orchestra can run inside the same network of your XS/XCP-ng hosts, while you can access it from outside (unlike XenCenter).

**Comment by borzel** [comment]
We should collect all infos here: https://github.com/xcp-ng/xenadmin/wiki/Cross-Platform-Vision

**Comment by borzel** [comment]
First Prototype here: https://github.com/borzel/xenadmin/releases/tag/v7.4.0-Linux-alpha

Please test and report!

**Comment by borzel** [comment]
I did a PR against upstream for building dotnet-packages on mono/linux: https://github.com/xenserver/dotnet-packages/pull/69

**Comment by borzel** [comment]
Here are the nightly builds of the linux/mono prototype: https://builds.schulzalex.de/xcp-ng_linux-prototype

**Comment by gangsterrapper22** [comment]
I tried to run this on OS X with mono but there it doesn't work. Maybe I can try to compile your source code on OS X with mono. Maybe it works then.

**Comment by borzel** [comment]
To run it on OS X it need's additional work, which I can not do. I don't own an apple device :-)

**Comment by borzel** [comment]
After several problems with gui elements from winforms I try to run XCP-ng Center against a debug build of mono... maybe I find something...

**Comment by borzel** [comment]
First goal is to get it running on Ubuntu 18.04 with newest Mono release

**Comment by borzel** [comment]
tweaked mono and my prototype a bit and now the General Tab is kind of working :-)

![grafik](https://user-images.githubusercontent.com/5782951/42136610-1c0956ae-7d5f-11e8-880e-0286b757c56d.png)

**Comment by alejandro-anv** [comment]
I downloaded de lastest build from https://builds.schulzalex.de/xcp-ng/linux-prototype/ but can't even start it.
When I run mono XenCenterMain.exe I receive this mesage in console. 

Missing method System.Array::Empty<[1]>() in assembly /usr/lib/mono/4.5/mscorlib.dll, referenced in assembly /home/anv/Descargas/xcp/xcp-ng-linux-prototype-23/XenModel.dll

My version of mono is:

$ mono --version
Mono JIT compiler version 3.12.1 (tarball Tue Jan 12 19:13:02 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by borzel** [comment]
@alejandro-anv you should use the latest development version of mono.

**Comment by borzel** [comment]
So what's your question? It misses log4net...

**Comment by kallisti5** [comment]
Seems to be missing a lot more than just log4net.  Attempting to open XenCenter.sln in MonoDevelop 5.10 results in a crash.

**Comment by kallisti5** [comment]
Tried again on Monodevelop 7.3.3 (via flatpak).
Man, I can't believe it has been almost 5 years and my original description of what dependencies are needed in Mono are still valid:

https://github.com/xenserver/xenadmin/issues/3#issuecomment-47696406

dotnet is really a poor ecosystem on Linux :-|

**Comment by kallisti5** [comment]
Updated for xcp-ng:

**XenCenterLib**:
* DotNetZip
* log4net

**XenCenterVNC**:
* log4net

**XenModel**:
* log4net
* XML-RPC.net - old 2.x
* Newtonsoft.Json (new for xcp-ng?)

**XenOvfApi**:
* log4net

**XenOvfTransport**:
* log4net
* Discutils
* UNKNOWN: RegexStringValidator
  * https://apisof.net/catalog/System.Configuration.RegexStringValidator
  * Had to "remove" References/System.Configuation and re-add it to project :-|

**Comment by kallisti5** [comment]
With the steps above, down to this:

![1](https://user-images.githubusercontent.com/100110/49401217-278cb080-f70c-11e8-9360-d9a4981596f7.png)

**Comment by borzel** [comment]
Maybe on the weekend I find some time to help you out...

**Comment by kallisti5** [comment]
I'd say this... focusing on the development of xenadmin in Mono vs Microsoft Visual Studio would help long-term multi-platform support.  XenAdmin is *really* close to running on Linux and OS X via Mono. Since Mono is now owned by Microsoft, maybe just focus development for Windows, Linux, and OS X in it? Citrix tried building in Visual Studio *and* Mono as a second-class citizen, but it never really worked out.

One *BIG* roadblock using XenServer has always been its lack of cross-platform support.  ESX suffers the same fate, but is kind of an industry standard now.  For XenServer / XCP to compete, it really needs to do something "better" then vmware's offerings.  A native cross-platform management UI could easily be that thing.  vmware is rapidly working on their HTML5 console, and it is almost feature complete.

**Comment by olivierlambert** [comment]
@kallisti5 I can't understand your statement: what about Xen Orchestra? I mean, that would make sense if XO wasn't there, but it's a fully features HTML5 console with all XC features plus backup and ACLs/cloud-like stuff. I'd be happy to hear what's missing there that you are forced to stay on XenCenter/XCP-ng Center.

**Comment by borzel** [comment]
Just build it from sources and you have all the features. Aside from that I also miss the "tree" in XO, but aside from that it's pretty cool.

Back to the linux client: I would be happy if you will help on that. I just have limited ressources to push it faster.

**Comment by olivierlambert** [comment]
Meh.

1. You didn't even take the time to update the appliance to the latest version (this version is almost 1y old)
2. You didn't read the doc explaining how to install it from the sources to get all features for free

**Comment by kallisti5** [comment]
@borzel I wonder if the solution here is having a separate+dedicated Mono project file until Microsoft comes up with some "one SDK to rule them all" for Dotnet?

**Comment by minblock** [comment]
I don't know if I should put another pull request, but the Domain Join is broken as hell. I don't know if it is because my domain is misconfigured or the Build for the active directory join is outdated. I will do some more tests and get back to you

**Comment by olivierlambert** [comment]
@kallisti5 No worries, I know it's not about discrediting. I just feel there is probably a lack of understanding on XO project :)

Xen Orchestra (on XAPI) exists since... 2013! There is a dedicated team working on it (6 ppl, full time). And it's fully Open Source - aGPLv3- (all issues are on GitHub, unlike XenCenter, which is only developed by Citrix) with a reasonably sized community (forum, users, community scripts etc.)

Just check the pulse/stats on the repo: https://github.com/vatesfr/xen-orchestra/pulse/monthly

Also, XO has a far more broader scope: it's not "just" an admin tool, but it's able to do auto patching, streaming VMs on any pool, backup, incremental delta backup, ACLs, self service with quotas, advanced stats and much more. There is also an API, and a CLI! It could also act as a proxy to only expose one XO and not all the XAPI behind a firewall.

That's why I'm convinced there is already a *de facto* cross platform solution, and contributing to it directly seems to be less a dead-end than tinkering/bending an app to make it work on Linux despite there is no effort from the Citrix core-contributors to make it real (and on a far more limited features scope).

What I meant in the end: your time could be used instead to create tickets on XO tracker about a feature you'd like to have in XO that you like in XenCenter (or you'd like to have in XenCenter in the first place). A simple real recent example? In [this ticket](https://github.com/xcp-ng/xenadmin/issues/121) someone asked for pause/unpause feature exposed in XCP-ng Center. One week later, it was available in the next XO release. I think it speaks for itself about what you can expect for it.

At least it should answer the "there is no HTML5 admin console for XCP-ng and it's a BIG blocker", right?

**Comment by borzel** [comment]
please continue the XO discussion in a separate thread elsewhere...

Here I want just content for linux xenadmin :-)

**Comment by derrickmehaffy** [comment]
@borzel I agree with you, this thread should remain only about linu xenadmin. @olivierlambert not basing you or anything, XO is a great tool. Many of us just like the layout of xenadmin better. The structure is a bit more "admin focused".

**Comment by olivierlambert** [comment]
@derrickmehaffy I'd like to have your input about "more admin focused", because I'm an admin myself and I'm not sure to get it. We'd be happy to improve XO to go in the way you like.

**Comment by sammcj** [comment]
Really keen to see this work out, if anyone needs someone to test a build against a cluster let me know and I'll see what I can do.

**Comment by borzel** [comment]
@BlackCentipede @cocoon here is the new branch where we sum up all linux/mono-releated results

https://github.com/xcp-ng/xenadmin/tree/feature-linux-8.0

**Comment by BlackCentipede** [comment]
Yep, put all code you have so far into it and we can figure out the milestones together on what each of us need to do from this point on.

**Comment by borzel** [comment]
ok, sounds good. I try to do this ASAP, but I'm on vacation from Feb 10 (Sunday) till Feb 13 (Wednesday)

**Comment by cocoon** [comment]
I have seen you removed the "feature-linux-8.0" again but I have seen these:

master-linux-dev-borzel
master-linux-dev
master-linux

So I will wait until you have the startable prototype branch ready and give a go?

I reactivated and updated my Ubuntu 16 + Mono Development VM (MonoDevelop v7.6 build 711).


**Just some thoughts:**

Do we want to have the same environment? 
Then you could tell the used environment and needed packages and version numbers to document it.

And maybe I can then create a wiki entry about it and lazer automate building an development VM/Appliance with packer, that could make it easier for others to jump in and try to fix something.

**Comment by BlackCentipede** [comment]
We also need a mode of communication to actively discuss on this, do we need to discuss it here or do we move it to chat program like Slack, Discordapp, or anything?

**Comment by borzel** [comment]
@cocoon @BlackCentipede

I would prefer IRC for communication, I've already set up a quassel server. That works very well.

You can just join #xcp-ng-dev on irc.freenode.net - my quassel server is always online and I read every day through the chat. There we can discuss the future and open a separate channel... do you know how to do that on IRC? :-) name should be something like `xcp-ng-xenadmin-dev`

yes, I did some tidy up to get started. Now we have a real `master` branch with all current changes in it as a base. My plan is to fill `master-linux-dev-borzel` with my current state of the port which is here: https://github.com/borzel/xenadmin/tree/linux-7.4

That should happen till next weekend... maybe ;-) You can also create your own branch and play around... thats always my best source of ideas.

Environment:
* Ubuntu 18.04 (optional)
* latest mono-dev you can get
* latest monodevelop you can get

I documented the steps to get it running: https://github.com/xcp-ng/xenadmin/wiki/Cross-Platform-Vision#first-hack-by-borzel
You can start there and try to follow it and add up as you do it.

See you in the IRC!

**Comment by borzel** [comment]
Some more info from my dev system:

```
# mono -V
Mono JIT compiler version 5.16.0.220 (tarball Mon Nov 26 17:17:59 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)

```

**Comment by BlackCentipede** [comment]
Yep, I'll come on this weekend to talk more on what we should do from here.

**Comment by borzel** [comment]
For all who just want to run this:
https://github.com/xenserver/xenadmin/issues/3#issuecomment-460441876

**Comment by carragom** [comment]
Hi @borzel, I was wondering if with the arrival of WindowsForms in .netcore 3.1 it would make more sense to try and port the project to .netcore instead of mono.

**Comment by olivierlambert** [comment]
@carragom FYI:

* XO 6 will bring a UI more similar to XCP-ng Center
* we have some plans for a basic/simple XO directly embed in XCP-ng

So if there's a reason left for using XCP-ng Center, let me know. Ideally, I'd like to get completely rid of it to reduce number of XAPI clients to maintain.

**Comment by carragom** [comment]
@olivierlambert 
I stated the reasons why I prefer XCP-ng Center [here](https://xcp-ng.org/forum/topic/962/why-are-you-using-xcp-ng-center/101?_=1576433916396). IMO I would love to see XO as an electron app that I could carry around in my laptop where all I have to do to connect to a new pool is add a server.

Having XO embedded into XCP is a really good step forward. But still use cases remain. For example cross pool VM movement. How would I go about moving a VM across different pools in this embedded scenario?

**Comment by schulz-alexander** [comment]
@carragom Hey! So good it sounds, xenadmin / XenCenter / XCP-ng Center don't use only Winforms, most of the UI elements are drawn from scratch.

Big pain. Not worth it :-(

**Comment by carragom** [comment]
@borzel I see. But do you still think it would be easier to port all that to mono instead .netcore ? If you say yes I believe you. Just wanted your opinion on the matter.

**Comment by schulz-alexander** [comment]
actually I don't have any opinion ... no real spare time to do anything :-(

**Comment by carragom** [comment]
don't worry and thanks for the great work

**Comment by olivierlambert** [comment]
@carragom no problem to add other pool as the app will run in your browser. However, it will be likely not saved (or we need to store some info in your browser itself). I think this is doable :)

**Comment by carragom** [comment]
@olivierlambert great to know, I'll keep an eye on the project and give a try when available

**Comment by mimi89999** [comment]
I have an issue with XCP 8.0.0. It is crashing on the splash screen. Would it be possible to add an option to disable splash?

**Comment by cocoon** [comment]
You could run XenCenterMain.exe instead, that would avoid the splash?

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
