### ISSUE TITLE
This version of XCP-ng Center is out of date

### ISSUE THREAD

**Issue by Finallf** [xcp-ng/xenadmin#230]
**After this update:**
https://xcp-ng.org/forum/post/75983

**This error occurs:**
```
"Failed","Refused connection to xcp1
This version of XCP-ng Center is out of date and cannot connect to xcp1.

You can get a compatible version of XCP-ng Center from the following location:
","","Apr 23, 2024 11:09 PM"
```

**Comment by gb-123-git** [comment]
+1 Getting the same error. This may be due to Xen upgrade to 4.17

**Comment by gb-123-git** [comment]
@borzel @michael-manley 

Anyone working on this ?
Any chance of getting this fixed ? (Somehow I feel this is going to end up as abandonware) 😞

**Comment by michael-manley** [comment]
Hello,

I am working on it but I am currently dealing with a server migration that is eating my time. I'll try to take some time today to look at this.

**Comment by gb-123-git** [comment]
@michael-manley 
Thanks.
Btw, this only happens when update patches are installed. When base 8.3 beta 2 iso is installed, xencenter can connect.

**Comment by gb-123-git** [comment]
@michael-manley - Any Updates on this ?

**Comment by cocoon** [comment]
you can try my build until it is fixed, for me it can connect with latest updates, maybe same for you:
https://github.com/xcp-ng/xenadmin/issues/213#issuecomment-1872827898

**Comment by michael-manley** [comment]
Hello All,

I think I have a fix but I need to create my XCP-ng environment I used for testing.

**Comment by michael-manley** [comment]
Everyone,

Looks like the API Version jumped again to 2.21, I added this to the Enums dealing with the API and now it allows connection. This is fixed with changeset cd4c62ee vNext build 24144

**Comment by gb-123-git** [comment]
@borzel @michael-manley 
is there any place from where the builds can be downloaded ? or would I need to build from sources ?

**Comment by cocoon** [comment]
You can look at the "actions" and there in "artifacts" if there are files available from the build action:

https://github.com/xcp-ng/xenadmin/actions/runs/9204101800#artifacts
