### ISSUE TITLE
nightly build 99.99.99.30 not working with latest api

### ISSUE THREAD

**Issue by ionutnechita-intel** [xcp-ng/xenadmin#232]
# rpm -qa | grep xapi
xapi-rrd2csv-24.11.0-1.3.xcpng8.3.x86_64
xapi-core-24.11.0-1.3.xcpng8.3.x86_64
xcp-ng-xapi-plugins-1.10.0-1.xcpng8.3.noarch
xapi-xe-24.11.0-1.3.xcpng8.3.x86_64
xapi-nbd-24.11.0-1.3.xcpng8.3.x86_64
xapi-tests-24.11.0-1.3.xcpng8.3.x86_64
python2-xapi-storage-24.11.0-1.3.xcpng8.3.x86_64
xapi-storage-script-24.11.0-1.3.xcpng8.3.x86_64

#  xl info
host                   : xen-xcp-ng-server-1
release                : 4.19.0+1
version                : #1 SMP Tue Apr 16 18:07:56 CEST 2024
machine                : x86_64
nr_cpus                : 16
max_cpu_id             : 15
nr_nodes               : 1
cores_per_socket       : 16
threads_per_core       : 1
cpu_mhz                : 2419.224
hw_caps                : bfebfbff:7ffaf3ff:2c100800:00000121:0000000f:239c27eb:9840078c:00000100
virt_caps              : pv hvm hvm_directio pv_directio hap iommu_hap_pt_share vmtrace gnttab-v1 gnttab-v2
total_memory           : 65323
free_memory            : 24990
sharing_freed_memory   : 0
sharing_used_memory    : 0
outstanding_claims     : 0
free_cpus              : 0
xen_major              : 4
xen_minor              : 17
xen_extra              : .3-4
xen_version            : 4.17.3-4
xen_caps               : xen-3.0-x86_64 hvm-3.0-x86_32 hvm-3.0-x86_32p hvm-3.0-x86_64
xen_scheduler          : credit
xen_pagesize           : 4096
platform_params        : virt_start=0xffff800000000000
xen_changeset          : 949a4aad4176, pq 4f8cbaa4a111
xen_commandline        : dom0_mem=4288M,max:4288M watchdog ucode=scan dom0_max_vcpus=1-16 crashkernel=256M,below=4G console=vga vga=mode-0x0311
cc_compiler            : gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
cc_compile_by          : mockbuild
cc_compile_domain      : [unknown]
cc_compile_date        : Tue Apr 16 18:38:59 CEST 2024
build_id               : a8640618c1c5f907fd04bb2a8d6a1bcabff71d1d
xend_config_format     : 4

#  lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    16
Core(s) per socket:    1
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 151
Model name:            12th Gen Intel(R) Core(TM) i9-12900
Stepping:              2
CPU MHz:               2419.224
BogoMIPS:              4838.44
Hypervisor vendor:     Xen
Virtualization type:   para
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              30720K
Flags:                 fpu de tsc msr pae mce cx8 apic sep mca cmov pat clflush acpi mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid pni pclmulqdq monitor est ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 bmi2 erms rdseed adx clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 gfni vaes vpclmulqdq rdpid arch_capabilities

![xcp-ng-8 3-beta-today-Center-June-2024](https://github.com/xcp-ng/xenadmin/assets/84138529/7379c672-2294-48f8-96e3-0ca6ba3859c3)

**Comment by Seneken** [comment]
After yum update via command on xcp-ng 8.3 beta 2, now I can't connect to my xcp-ng server with this xcp-ng center builds :(

**Comment by tdcockers** [comment]
Yes same problem here. I made more issues for myself because I updated this a week ago, but only found it today after I updated the OS underlying XOA and now can't access a console for my XOA host anywhere and can't roll back to an older snapshot from anywhere...
