### ISSUE TITLE
Not compatible with xcp-ng 8.3.0 RC1

### ISSUE THREAD

**Issue by SonGokuSSJ** [xcp-ng/xenadmin#233]
When I try to connect to my updated server I get a message, that I need an updated version of XCP-ng Center to be able to connect to the updated server. 

![image](https://github.com/user-attachments/assets/7daf928f-9668-436e-9e01-21f2e2cf35a9)

**Comment by michael-manley** [comment]
Again! Why does it seem every release the API Version changes. I'll try to get another build with that fixed out.

**Comment by SonGokuSSJ** [comment]
Dunno, cannot say anything about that. I only just updated to 8.3.0 RC1 and tested it out. 

Thank you for looking into it.

**Comment by michael-manley** [comment]
![image](https://github.com/user-attachments/assets/ed18bc7f-c2e6-4278-aeaa-6953333dd84d)
Current sources work fine. I was able to connect to 8.3 RC1

I attached my build here since the one in build artifacts is expired.
[net481.zip](https://github.com/user-attachments/files/16689376/net481.zip)

**Comment by ecoutinho** [comment]
Hi Michael,

 I had the same issue using nightly build 99.99.99.30, but with the version you sent I was able to connect to 8.3 RC1. Thanks for the update!

**Comment by SonGokuSSJ** [comment]
The attached version also works for me for the new RC1 environment.
