### ISSUE TITLE
Get Tests running

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#24]
- [x] Use Nunit ffrom NuGet
- [x] Use Moq from NuGet
- [x] Adapt XenAdminTests to Nunit 3.0
- [x] port changes to master!!
- [ ] Get them running inside Jenkins and publish reports
- [ ] Get all passing

**Comment by borzel** [comment]
Tests are running ...

![grafik](https://user-images.githubusercontent.com/5782951/38759276-62151ee4-3f75-11e8-8ec8-bbf8cdf2ae55.png)

**Comment by borzel** [comment]
48 failed test :-|

![grafik](https://user-images.githubusercontent.com/5782951/39023451-ff5b3106-443a-11e8-960d-284a8c5ddce7.png)

**Comment by borzel** [comment]
cool, that's working

**Comment by borzel** [comment]
We are getting closer...

![grafik](https://user-images.githubusercontent.com/5782951/39958182-cb523676-55ff-11e8-9175-946bc6d145a8.png)

**Comment by cocoon** [comment]
Yes one of the dialog tests is I think trying to get from the Update Screen to the next Select Servers screen, but we have no update URL I think ... will check that when I have time again ^^

**Comment by cocoon** [comment]
Just to confirm, you added an Update-URL, this fixed one of the tests.

**Comment by cocoon** [comment]
The test in "LicenseManagerSummaryLicenseExpiresDecoratorTests.cs" has a fixed date string that is compared to the generated expire date, but on my system it will return the month name not in US language.

So you would need to fix the test OS environment + software to comply with the test (I think all should be en-us?)

Fixed date string: "October 25, 2025"
https://github.com/xcp-ng/xenadmin/blob/master-7.4/XenAdminTests/LicensingTests/LicenseManagerSummaryLicenseExpiresDecoratorTests.cs#L65

Or hack it to generate the month name, but that would modify the test as it really wants to have "October".

The hack for that line would be:
```
Contains = System.Globalization.CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(10) + " 25, 2025"
```

**Comment by cocoon** [comment]
To have an environment in en-US would solve all but one final Test (ExportVMActionTest).

I have one possible fix as code that could be discussed:

```
            // Change current culture to en-US as some tests expect it
            // this requires DotNet v4.5+
            System.Globalization.CultureInfo culture;
            culture = System.Globalization.CultureInfo.CreateSpecificCulture("en-US");

            System.Globalization.CultureInfo.DefaultThreadCurrentCulture = culture;
            System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = culture;

            System.Threading.Thread.CurrentThread.CurrentCulture = culture;
            System.Threading.Thread.CurrentThread.CurrentUICulture = culture;
```

If you insert this code block as first line here:
https://github.com/xcp-ng/xenadmin/blob/master-7.4/XenAdminTests/DialogTests/DialogTest.cs#L47

it will force the CultureInfo to be en-US and the DateFormat will be OK for the Dialog tests.

But that would modify the program, and I think the clean solution should be to test it on a system that is fully localized in en-US.

**Comment by borzel** [comment]
I added just this on failing test to get them running in en-us:

 [SetCulture("en-EN")]


Example:

https://github.com/xcp-ng/xenadmin/blob/0742c56b8ee846bb05625d9cc67687d1c25fdf7e/XenAdminTests/Controls/SrPickerItemTests.cs

**Comment by cocoon** [comment]
Oh yes that's much more efficient.

And I fail to solve the [ExportVMActionTest](https://github.com/xcp-ng/xenadmin/blob/0742c56b8ee846bb05625d9cc67687d1c25fdf7e/XenAdminTests/XenModelTests/ActionTests/ExportVMActionTest.cs#L32).

The temporary file is generated in root folder of the whole solution
xenadmin\xxxx.xva.tmp

It somehow fails to work with the stream using the simulatorproxy, but I didN#t findout the root cause.

**Comment by borzel** [comment]
I'm about to prepare a branch for master, which we can later PR to Citrix:
https://github.com/xcp-ng/xenadmin/tree/feature-nunit2-to-nunit3

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
