### ISSUE TITLE
Demo mode without real hosts

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#25]
I discovered in the automated test, that we can run it without real hosts.

So I created a new VS Project called XenAdminDemo. At startup you have to point to a state.xml file ( which holds a whole pool information). Such files can be found in `XenAdminTests\TestResources`.

This is ideal to develop gui features without the need to have real XCP-ng hosts.

**Comment by cocoon** [comment]
Thanks for the hint, have not seen this!

**Comment by borzel** [comment]
It's even better: https://support.citrix.com/article/CTX130396

**Comment by borzel** [comment]
because we can use this "feature" without any modification, i close this

**Comment by borzel** [comment]
Doku: https://github.com/xcp-ng/xenadmin/wiki/Play-around-without-Server-%28Demomode%29
