### ISSUE TITLE
Plugins as dotnet dll

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xenadmin#26]
One thing that I would like to see would be an intelligent dynamic way of adding support for modifications / Plugins that can be written in csharp.

Currently (afaik) the official plugin system only allows external applications and web tabs etc.
Of course I can modify the source code but to make it available to others or to keep it compatible with future versions (+ still easy to merge) is not easy.

So this is more of a wishlist item if there will ever be someone who has already done something like this and find the mood to start this.

One thing that I already have working is a plugin that is showing information of fibre channel adapters as I often want to see WWN of the servers or something else. But to diplay it in the General tab I have to hard code it into the source code if I want to do it with csharp.
(maybe I will write a small tutorial in the wiki later about the plugin if there is any interest, will be away for a week)

**Comment by cocoon** [comment]
If you want to test and fix any mistakes I made, I just started the wiki already before I forget it ^^
https://github.com/xcp-ng/xenadmin/wiki/%5BDRAFT%5D-Create-a-custom-Server-Plugin-(example)

**Comment by borzel** [comment]
I would highly prefer a solution for both XCP-ng Center and XenOrchestra:
Something like a standardized API where you can put your script into XCP-ng Server (Master?) and we can get the results/output over XAPI.

**Comment by cocoon** [comment]
Yes this request here is more about for example how to display the results of the server plugin in the XCP Console.

Just improved the server plugin example and did test it on real hardware with XenServer 7.2.

**Comment by cocoon** [comment]
But it might still be the easier solution to create a separate program in csharp and just call it from the context menu like these:

https://www.citrix.com/blogs/2018/03/14/xenserver-plugins-collection-v6/

**Comment by cocoon** [comment]
I got a prototype ready, will let you try it the next days.

**Comment by cocoon** [comment]
Here it is, first example plugin:
https://github.com/cocoon/xcpng.example.plugin

Still some to dos, will try to write something about it in the wiki.

While reading the example plugins, especially the powershell one, I figured out that XCP-NG Center is calling the plugins with parameters and that contains the session information so you can directly use this in any dotnet application.

**Comment by borzel** [comment]
Cool, it works! Now we can have fun :-) Thank's!

![grafik](https://user-images.githubusercontent.com/5782951/40943280-c2ffe550-6850-11e8-8ff5-92eca5e1e5f2.png)

**Comment by borzel** [comment]
By the way, I builded your plugin without the XenServer SDK, just added the `XenAdmin\XenModel\XenModel.csproj`

**Comment by cocoon** [comment]
Great, thanks for trying and reporting back!

Currently I am totally busy with some projects @ work and some private stuff, hope to find the time soon to add it to the wiki and I already have some improvements for an advanced example with async loading nearly finished, that only "needs more love" <-- I love this label ^^

**Comment by borzel** [comment]
Here's your label ;-)

**Comment by cocoon** [comment]
so atleast I uploaded now my second example plugin:
https://github.com/cocoon/xcpng.example.plugin/tree/master/xcpng.example.plugin2

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
