### ISSUE TITLE
XenAdmin updates url

### ISSUE THREAD

**Issue by unusual-aspect** [xcp-ng/xenadmin#29]
When you install '[last](https://github.com/xcp-ng/xenadmin/releases/tag/v7.4.0.3-beta-MSI)' release and navigate to Notifications panel, then try to update, it show that URI is empty.

AFAIK this still is WIP mode, so i like to just point that one issue to cover in next releases ;)

**Comment by borzel** [comment]
I set the update url in RC3 to this temporarly github url, to have more "informed" installations out there

**Comment by skajter** [comment]
Is this XenAdmin, will have also yum updates? I mean, when i go to XCP 7.5, and have some updates to install ,there no message in XenCenter that are available.

**Comment by olivierlambert** [comment]
You have those in XO: https://xen-orchestra.com/blog/xcp-ng-updates-from-xen-orchestra/

**Comment by schulz-alexander** [comment]
the update.xml moved from the main xenadmin repo to a separate repo: https://github.com/xcp-ng/xenadmin-updates
