### ISSUE TITLE
Create XCP-ng Branding

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#3]
Create own Branding
- [X] Be able to modify text
- [ ] Overwrite URLs to https://xcp-ng.github.io or leave empty
- [x] Overwrite pictures

**Comment by olivierlambert** [comment]
Legal question: can someone check, in a GPLv2 software (or here BSD2), if copyright should be kept or removed? (trademarks != copyright)

**Comment by olivierlambert** [comment]
I suppose we should keep the Citrix copyright in source files (as possible) and remove trademarks (XenServer/XenCenter). I'm asking some lawyers around.

**Comment by borzel** [comment]
Merging should also be easier with the copyright in the source files.

**Comment by borzel** [comment]
It seams that Trademarks can also be set to what we want. Have to look deeper into this.

**Comment by olivierlambert** [comment]
Nice job!

**Comment by olivierlambert** [comment]
Feel free to use XCP-ng logo we made :)

**Comment by borzel** [comment]
@olivierlambert Can you point me to raw image "sources"?

**Comment by borzel** [comment]
@olivierlambert I'll use this https://github.com/xcp-ng/xcp-ng-plymouth-theme/blob/master/background.png and some pictures from the webpage.

**Comment by olivierlambert** [comment]
Sure go ahead, it's here for this purpose!

**Comment by borzel** [comment]
![grafik](https://user-images.githubusercontent.com/5782951/38470845-0a01677c-3b69-11e8-908c-55d797c5af13.png)

![grafik](https://user-images.githubusercontent.com/5782951/38470838-f7fa1858-3b68-11e8-9144-4c74e123c10c.png)

**Comment by borzel** [comment]
![grafik](https://user-images.githubusercontent.com/5782951/38471659-8cff57f0-3b74-11e8-9c79-291cb1a5c8ad.png)

**Comment by borzel** [comment]
Everyone can now build XCP-ng Console --> https://github.com/xcp-ng/xenadmin/pull/10
