### ISSUE TITLE
Console Screen : Debian VM intermittent response

### ISSUE THREAD

**Issue by thowden** [xcp-ng/xenadmin#30]
Hi,  

I have just upgraded a XenServer 6.5 to XCP 7.4 and built a new Debian 8.4 VM on it. 
Using XCPAdmin and the Console view to access the VM I am experiencing the console not responding unless I modify by undock / redock, scale / not scale, etc. Sometimes the keyboard is active and other times its not. Cannot determine a pattern and have not tried any other VM, but I have to assume it is in the XCPAdmin build. Just reporting, not complaining. Appreciate the efforts so far. 

cheers
Tony

**Comment by borzel** [comment]
Can someone check this with XenServer 7.4 and XenCenter 7.4?

**Comment by borzel** [comment]
So i can close this?
