### ISSUE TITLE
Warning message (Unlicensed) - enhacement

### ISSUE THREAD

**Issue by xiscoj** [xcp-ng/xenadmin#32]
hi,
when connecting to a pool it says (Unlicensed) on red and there is a orange warning triangle in my pool and servers. It was alarming the first time until noticed is the license issue. Maybe you could change to Community Edition and not show a warning?

**Comment by skajter** [comment]
If you using Citrix XenServer then you will have that warning if was not licenced. On case where you install NG version all limitations are taken off, so you have full licenced (if we can call this way), product.

XenCenter (Citrix and NG), is just a client to 'server', this is not limitation of client itself, but more on server part.

**Comment by xiscoj** [comment]
hi, I know there are no limitations on NG. Only say that xcp-ng console says unlicensed on the main windows. Xencenter console  showed this only in license menu.
