### ISSUE TITLE
Tidy up main project files

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#34]
* MAINTAINERS
* LICENSE
* CONTRIB

**Comment by borzel** [comment]
@olivierlambert @gangsterrapper22 anything else to do?

@cocoon do you want to join our team?

To the world: Anyone else want to join?

**Comment by cocoon** [comment]
@borzel sure why not, maybe there is the one or other thing I can still help with

**Comment by borzel** [comment]
Updated master and master-7.4 branch. This should do it for now.
