### ISSUE TITLE
XenCenter installed via host (based on XCP-ng 7.4 iso) fails to work

### ISSUE THREAD

**Issue by rhtyd** [xcp-ng/xenadmin#36]
I'm getting connectivity issue that the platform is not supported when I add a xcp-ng 7.4 host to xencenter it.

**Comment by borzel** [comment]
can you descripe it a bit more in detail?

Citrix XenCenter has no support for XCP-ng. You have to use this: https://github.com/xcp-ng/xenadmin/releases/tag/v7.4.1-MSI

**Comment by rhtyd** [comment]
Thanks will try that, /cc @PaulAngus @DagSonstebo
