### ISSUE TITLE
XCP-ng Center have invalid url on server website.

### ISSUE THREAD

**Issue by skajter** [xcp-ng/xenadmin#38]
I just updated my test server to new 7.4 release from 'news' iso, and when you try to download XCP-ng Center, it show invalid url.

"Not Found
The requested URL /XCP_ng_Center_Installer.msi was not found on this server.

Xapi Server"

From full url: https://192.168.0.15/XCP_ng_Center_Installer.msi

**Comment by skajter** [comment]
https://github.com/xcp-ng/xcp-ng-release/blob/master/src/xenserver/opt/xensource/www/XCP-ng-index.html

What we searching for is: 

"<li><a href="XCP_ng_Center_Installer.msi">@BRAND_CONSOLE@ installer</a></li>"

Not sure how and where i can find this variable to update path (if even exist)

**Comment by skajter** [comment]
Oh ... someone already done request:

https://xcp-ng.org/forum/topic/58/xcpcenter-installer-link-not-found

**Comment by olivierlambert** [comment]
@BRAND_CONSOLE@ is replaced by the branding build package. The problem is not the link, it's finding which package embed it in XCP-ng during install.

**Comment by borzel** [comment]
So this is not an error of XCP-ng Center itself

**Comment by stormi** [comment]
This is now fixed in upcoming XCP-ng 7.5 :)
