### ISSUE TITLE
Remove Citrix Insight Services

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#4]
Should we do that?

**Comment by borzel** [comment]
Should we do that?

**Comment by koumdros** [comment]
I would be loath to lose that as it is great for a quick health-check, but you might be right from a legal standpoint, plus at some point Citrix might get antsy about it use.

Or we can loby them to opensource it :)

**Comment by olivierlambert** [comment]
I think there is no way they accept that :p But, I'm open to the idea to do it specially for XCP-ng. We'll maybe offer this kind of service for XCP-ng Pro or even with a free registered tier.
