### ISSUE TITLE
abstract native calls

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#40]

**Comment by johnbester** [comment]
I have created cross platform native call classes to allow using dlls in Windows and some other functionality in other operating systems. Since I am not registered as a developer, I would appreciate it if someone can integrate these files into the project. On their own they should be completely harmless and should only have an effect once native calls are replaced with calls to NativeCall class. Please see attached.
[nativecalls.zip](https://github.com/xcp-ng/xenadmin/files/1984676/nativecalls.zip)

**Comment by borzel** [comment]
I did exacty what you sad here in my prototype:

https://github.com/borzel/xenadmin/blob/linux-7.4/XenCenterLib/NativeCalls.cs
https://github.com/borzel/xenadmin/blob/linux-7.4/XenCenterLib/INativeCalls.cs
https://github.com/borzel/xenadmin/blob/linux-7.4/XenCenterLib/NativeCallsLinux.cs
https://github.com/borzel/xenadmin/blob/linux-7.4/XenCenterLib/NativeCallsWin32.cs

Do you have a sugestion, how to implement these calls in linux?

For Example:

     [DllImport("gdi32.dll", EntryPoint="CreateCompatibleDC")]
     static extern IntPtr CreateCompatibleDC(IntPtr hdc);

Whats the same call in linux for that? So far I understand, Mono draw Winforms with System.Drawing. System Drawing used also native calls. So how does this work?

**Comment by borzel** [comment]
@johnbester by the way, thants for your zip archiv. I will review and include it. You can also fork and do a pull request :-)

**Comment by johnbester** [comment]
No - unfortunately not. I specialise in high level languages like Java and
do mostly server side and database programming. What I hoped to achieve was
to create a starting point which might get a developer with more low level
Linux experience involved. But you have to remember that the first step
(before getting to the Linux side of things) is to replace calls throughout
the system and first get it working on Windows. The way I would go about
this would be to run a code replace (using something like sed) to comment
out all old "extern" method declarations. This would cause lots and lots of
errors, but it makes it easy to find the places where replacements must be
made. Once you have that working fine under windows, then consider using
wine windows emulation libraries - you might be able to use the same calls,
but the application as a whole might then have to run in a wine environment.

**Comment by johnbester** [comment]
Actually, I am not so much interested in XenAdmin as I was a year ago. The
main reason being that when I was setting up a server with very specific
requirements I realised that Xen is only free when you start. When you need
2 or more USB devices passed through to a specific VM, you have to upgrade
to a very expensive Xen licence. Apart from that I needed to pass a video
card to a VM and I started looking at alternatives. At this point KVM is
doing exactly what I need and the only cost was research.

**Comment by borzel** [comment]
With XCP-ng this has now changed :-)

**Comment by BlackCentipede** [comment]
Ultimately, we need to get rid of manual rendering in GDI and the P/Invoke calls that aren't implemented in gdiplus that is provided by Mono: https://www.mono-project.com/docs/gui/drawing/

We would need to rely on Cairo or other existing rendering libraries for scaling images or rendering onto surface more.

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
