### ISSUE TITLE
Implement QuickDraw for linux/mono

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#42]
https://github.com/borzel/xenadmin/blob/linux-7.4/XenAdmin/Core/Drawing.cs

Instead of Win32-Call this works (in my prototype):

    public static void QuickDraw (Graphics gTarget, Bitmap buffer)
    {
        gTarget.DrawImage(buffer, new Rectangle(0, 0, buffer.Width, buffer.Height));
    }

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
