### ISSUE TITLE
VNC on Linux/Mono

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#44]
* [ ] create CustomCursor from Bitmap without native calls
* [ ] QueryPerformanceFrequency / QueryPerformanceCounter -> Use DateTime.Now?
* [ ] avoid using native calls in XenCenterVNC project

```
backGraphics.DrawImage(backBuffer, new Rectangle(dx, dy, backBuffer.Width, backBuffer.Height), x, y, backBuffer.Width, backBuffer.Height, GraphicsUnit.Display);
```

* [ ] Avoid call loop (RemoteConsole.Activate()) in XenAdmin\XSVNCScreen.cs -> CaptureKeyboardAndMouse()

* [ ] XenAdmin.Program [Main program thread] - Uncaught exception System.DllNotFoundException: Gdi32.dll  at (wrapper managed-to-native) XenAdmin.Controls.ConsoleTab.FullScreenHint.CreateRoundRectRgn(int,int,int,int,int,int)
* [ ] Avoid image addition in console window  (Paint black background first)

### Missing solutions

* https://github.com/xcp-ng/xenadmin/issues/54 Keyboard support
* https://github.com/xcp-ng/xenadmin/issues/41 Clipboard

**Comment by borzel** [comment]
### First VNC results

Every update on the image add's the content instead of simply overwriting it's part on the screen :-|

![grafik](https://user-images.githubusercontent.com/5782951/40028909-cb4eb1ca-57e1-11e8-8ea3-f87876056eab.png)

### Solution
The trick to get correct graphics is to paint black background before we paint the actual part of the image

```
Brush b = new SolidBrush(Color.Black);
backGraphics.FillRectangle(b, new Rectangle(x, y, width, height));
```

![grafik](https://user-images.githubusercontent.com/5782951/40028822-479c224a-57e1-11e8-95f5-f96373fc161b.png)

### Result

![grafik](https://user-images.githubusercontent.com/5782951/40028800-226a2efe-57e1-11e8-8e96-05708018fb95.png)

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
