### ISSUE TITLE
Rolling Pool Upgrade grayed out

### ISSUE THREAD

**Issue by scpcom** [xcp-ng/xenadmin#47]
If I connect my XenServer 7.2 in XCP-ng Center and try to run a Rolling Pool Upgrade the server is grayed out
I needed to go back to XenCenter 7.2 where I could run Rolling Pool Upgrade from XS 7.2 to XCP-ng 7.4.1.
This works for a single host but will not work for a multi-host pool because after upgrade is done, XenCenter 7.2 will be unable to connect to the server.

**Comment by borzel** [comment]
Workaround: Update pool manually.

**Comment by scpcom** [comment]
I forgot to add the feature request: :-)
Enable Rolling Pool Upgrade for free/unlicensed XenServer versions (at least for 7.0, 7.1 and 7.2).

**Comment by borzel** [comment]
Note to me: Should be related to the brand name change from "XenServer" to "XCP-ng" or something else in this area.

**Comment by scpcom** [comment]
I found that Citrix removed it in XenCenter 7.4 for all free/unlicensed versions.
Related code:
https://github.com/xcp-ng/xenadmin/blob/master/XenAdmin/Wizards/RollingUpgradeWizard/RollingUpgradeWizardSelectPool.cs#L200
https://github.com/xcp-ng/xenadmin/blob/master/XenModel/XenAPI-Extensions/Host.cs#L451

**Comment by borzel** [comment]
I published a pre-release: https://github.com/xcp-ng/xenadmin/releases/tag/v7.4.2-RC1

@scpcom Can you please test your rolling pool upgrade again?

**Comment by gangsterrapper22** [comment]
@borzel  I can create an Installer if needed but if this release is only for test then I think it is not needed.

**Comment by scpcom** [comment]
Rolling Pool Upgrade is possible now, but you need to place the required mini hotfixes inside XCP-ng folder:

> Could not find file 'C:\XCP-ng_Center_7.4.2.5-RC1_Binaries\RPU003.xsupdate'.

RPU002: XenServer 6.5
RPU003: XenServer 7.0
RPU004: XenServer 7.1 and newer

**Comment by borzel** [comment]
hhmm.... not sure about that, if we can include this files... I think not, because they are Citrix branded and so not easly redistributable.

In future we don't need these xsupdate files any more, because of the yum repo of XCP-ng.

@olivierlambert How do you plan to implement/enhance the rolling poll update feature of XCP-ng? Maybe it's possible to implement this per XAPI and use this for the rolling poll upgrade feature from XCP-ng Center and a new upgrade feature in XO?

**Comment by scpcom** [comment]
Yes, thats OK I think. They can be just copied from the XenCenter folder to XCP-ng Center folder before starting the Upgrade.
