### ISSUE TITLE
Understand build process

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#5]
https://github.com/xcp-ng/xenadmin/wiki/How-to-build

- [x] Create own brandingscripts

**Comment by cocoon** [comment]
You're on fire ^^

One thing that might need a note: 
The "splash" project requires a Windows SDK Version.

For example I had to manually change (select) it to 10.0.16299.0 and was 8.1 that isn't installed on my machine.

**Comment by borzel** [comment]
Branding Repo ist needed, like this: https://github.com/borzel/branding

**Comment by borzel** [comment]
Is anybody out there who allready knows the internals of the build process? or can point to some documentation?

**Comment by cocoon** [comment]
And there are a lot of custom fixes in additional packages (
https://github.com/xenserver/dotnet-packages) that makes it different to the packages from nuget like these:
https://github.com/xenserver/dotnet-packages/blob/master/patches/patch-json-net-JsonConvert.diff
https://github.com/xenserver/dotnet-packages/blob/master/patches/patch-json-net-JsonTextReader.diff
...
https://github.com/xenserver/dotnet-packages/blob/master/patches/patch-sharpziplib-ca-63358-TarInputStream.diff

**Comment by borzel** [comment]
I will try to build this without modifing any original source. wish me luck...

**Comment by olivierlambert** [comment]
@borzel and this is just XenCenter. Now imagine the same thing to build XCP-ng. No documentation, we had to almost reverse engineer all that stuff.

**Comment by borzel** [comment]
I was able to build "XenCenter" with the correct libraries and with my  own branding: https://github.com/xcp-ng/xenadmin/issues/3

**Comment by borzel** [comment]
Everyone can now build XCP-ng Console --> https://github.com/xcp-ng/xenadmin/commit/9ac1d80379b685aaf279b19c04aaba2ace7f34b7
