### ISSUE TITLE
Server upgrade: use XAPI Plugin

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#55]
https://github.com/xcp-ng/xcp/issues/34 XCP-ng update from XAPI

* check, if Rolling Poll Upgrade can do this

**Comment by schulz-alexander** [comment]
that's a big thing, not doable currently :-/
RPU will not work, it's more like a new implementation from scratch.

**Comment by schulz-alexander** [comment]
As I have no spare time I close this :-(
