### ISSUE TITLE
Implement splash in C#

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#56]
The splash of XenCenter/XCP-ng Center is written in C++. It would be easier to have it in C# to build it on mono.

* [x] Splash with image that starts XenCenterMain.exe
* [ ] Splash should show version number/text

This issue is intented to be resolved and implemented by a beginner and/or project newcommer!

**Comment by cocoon** [comment]
can be used and improved: https://github.com/cocoon/xcpng.splash

**Comment by borzel** [comment]
@cocoon you have now write acces, so you can add this into a feature branch (from master).
If you need help, I'm here :smiley: (... I'm still learning this git thing, but I'm getting better...)

**Comment by borzel** [comment]
Just compiled it, works :-)

Things that needs to be implemented:
* version number (AssemblyVersion, label on splash)
* internal naming (e.g. Form1 is not a good name)
* integration into XenAdmin.sln

**Comment by cocoon** [comment]
thx, you're quick ^^
some more open points:
- Branding spaceholders
- hardening while loop
- rename assembly

**Comment by cocoon** [comment]
just updated it with:

- showing Version on Splash
- renamed assembly to "XCP-ng Center.exe"
- renamed the form to SplashForm
- added some counters to break the while loop after a given timeout

**Comment by borzel** [comment]
![grafik](https://user-images.githubusercontent.com/5782951/43430179-ecf1b0c6-9467-11e8-908c-35bbf244caaa.png)

:-)

**Comment by cocoon** [comment]
- Branding spaceholders: **DONE**
- handle commandline arguments: **DONE**

Branding tested:

- copy only the project "splash-xcp-ng" folder to: xenadmin\splash-xcp-ng
(same level as original splash)
- added a reference to "splash-xcp-ng" in XenAdmin.csproj
(splash executable will get copied automatically to output folder)

- add splash-xcp-ng to brand-to-xcp-ng.sh: https://github.com/xcp-ng/xenadmin/blob/master/branding-xcp-ng/brand-to-xcp-ng.sh#L194
```
#AssemblyInfo rebranding
version_brand_csharp "XenAdmin CommandLib XenCenterLib XenModel XenOvfApi XenOvfTransport XenCenterVNC xe xva_verify XenServer XenServerHealthCheck splash-xcp-ng"
```
 
**Commandline Arguments**

There is an internal messagebox test in XenCenter implementet, so I used it to test passthrough of arguments like this:

```
"XCP-ng Center.exe" messageboxtest
```

This should display this messagebox:

![messagebox](https://user-images.githubusercontent.com/1071741/43999597-1224002c-9e10-11e8-9369-d7ff8fff19c5.png)

**Comment by cocoon** [comment]
added an own branch for it to try: https://github.com/xcp-ng/xenadmin/commits/splash-xcp-ng

**Comment by cocoon** [comment]
one thing that might be better: maybe we should not add it as a reference in XenAdmin but let in build by the solution and copy the files.

**Comment by borzel** [comment]
@cocoon  I'll include the new splash in XCP-ng Center 8.0

**Comment by borzel** [comment]
![grafik](https://user-images.githubusercontent.com/5782951/57572506-7eb15280-741b-11e9-8d44-c93e56972c4c.png)

**Comment by olivierlambert** [comment]
My 2 cents: should we add "Center" to make it clear that "XCP-ng" is the platform name, and "XCP-ng Center" a client?

**Comment by borzel** [comment]
good Idea!

**Comment by borzel** [comment]
![grafik](https://user-images.githubusercontent.com/5782951/57573203-61cd4d00-7424-11e9-8cdb-15985b8a588e.png)

**Comment by RoyNiyogabo** [comment]
It's really a good idea, it will be easy to tell the difference now.


Merci / Thanks
--------------------

*Roy Niyongabo*
*Data Science Consultant*

**Comment by olivierlambert** [comment]
Nice work @borzel

**Comment by cocoon** [comment]
Great, I see I have to read through some Updates. I am currently in Holidays in Bali.
