### ISSUE TITLE
Don't forget to stay close to mainline

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xenadmin#63]
Hi guys!

I see a lot of activity, and that's nice! But keep in mind that bigger the fork, harder it will be to follow the "mainline". Rebase your change, etc.

So try to push your changes in XenCenter repo too (1 PR per feature), this way it means less efforts for you in the end :+1:

**Comment by borzel** [comment]
In my opinion we did not implement new features, just changed things Citrix would not do.

I will have an eye on it and push changes to Citrix if it's not XCP-ng specific :-)

**Comment by borzel** [comment]
Sooo... I did one PR (https://github.com/xenserver/xenadmin/pull/2078) and prepared one issue (https://github.com/xenserver/xenadmin/issues/2079) for upstream. That's all we have today :-)

**Comment by borzel** [comment]
hm.... have to think about that a night or two ...

**Comment by olivierlambert** [comment]
That was a suggestion to get your life easier :) an also demonstrate to Citrix that a community can do good things ;) Personally, I'm not using this Windows client, so you are in charge here ;)

**Comment by borzel** [comment]
Maybe you use in future (so we can do it) our linux client

Offtopic: I would use XO more, but it's not so organized (treeview) like XenCenter and the UI has big fonts, etc. like these modern websites. Not efficient to keep multiple hosts/enviroments "visible". Yes, I know, I should create an issue on that ;-) working in mind on that for a while ...

**Comment by borzel** [comment]
Did my homework ;-)
https://github.com/xenserver/dotnet-packages/pull/69
