### ISSUE TITLE
Build MSI Installer for XCP-ng

### ISSUE THREAD

**Issue by gangsterrapper22** [xcp-ng/xenadmin#7]
I have created an MSI Installer with the XCP-ng compiled from this  Branch. The MSI File will create  an Desktop Shorcut and also an Shortcut in the Windows Start Menu.
 I have attached the MSI File there for testing. If it should be moved, please let me know.
 I have build the Installer with Visual Studio 2013 and the Microsoft Visual Studio 2013 Installer Projects. I have attached the MSI FIle as .zip. You just have to unpack it.  I think we also should make an own Branch with the Source Files for the MSI Installer.
[XCP-ng_x86.zip](https://github.com/xcp-ng/xenadmin/files/1881150/XCP-ng_x86.zip)

**Comment by borzel** [comment]
If I launch the desktop icon:
![missing_vc _runtime](https://user-images.githubusercontent.com/5782951/38380830-3730baa6-3905-11e8-9111-6624693d4e54.png)

But C:\Program Files (x86)\XCP-ng\XenCenterMain.exe works :-)

We should figure out how the real packaging works. There is a folder called WixInstaller in the sources, this is the way to go.

**Comment by gangsterrapper22** [comment]
I have just updates the MSI File in my first comment. I have compiled the program as Debug and not as Release, that is the reason why it ask for the .dll Files. The "D" in the Filenames stands for Debug. I tested it on another PC and I got no error message there when I have excuted it. Maybe you can try it again on your PC?

This MSI is just for test because the most programs are costing which can create MSI Files. I didn't look in the WixInstaller yet.

**Comment by borzel** [comment]
I know, installers are costly and/or limited. So I spend some time with WIX and NSIS at work someyears ago. NSIS was the way to go :-)

**Comment by gangsterrapper22** [comment]
I think an MSI is the easiest way to go, for example if you want to do an silent installation or something. I can try tomorrow or on the Weekend if I am able to Build an working Wix Installation MSI. Did my new created MSI work for you or do you still got some errors at the execution?

**Comment by borzel** [comment]
Actually I try to get the buildscripts working -> https://github.com/xcp-ng/xenadmin/wiki/How-to-build#build-with-buildscripts-work-in-progress

**Comment by gangsterrapper22** [comment]
Good Luck to get the Buildscripts working. I can try to make a better installer with Wix, that we have at least something, in case if the buildscripts aren't working.

**Comment by borzel** [comment]
After poking the bits and thinking about it, it would be nice if you @gangsterrapper22 could build an installer.

In the meantime, I will focus on getting this branding thing right, so that we have good sources to build the payload.

**Comment by gangsterrapper22** [comment]
I have created now an very Basic MSI Installer with Wix. I have uploaded the current source and an MSI File as Release to test if it works. You can find it here. https://github.com/gangsterrapper22/XCP-ng_Installer  On my test machine the Installation has worked.

**Comment by gangsterrapper22** [comment]
I have updated the Installer. It does now create an Desktop Icon and also one in the Startmenu. Is there anything else which should be implemented or is this enough for the first release for now?

**Comment by borzel** [comment]
I reorganized the repo, so you can now create a featurebranch from master. I would let the original folder/files untouched as much as possible, to stay mergable from upstream.

I think its better to create a new separate folder. What does @olivierlambert think about this?

**Comment by borzel** [comment]
@gangsterrapper22 payload for the installer: [XCP-ng_Console_7.4.0.1_x64.zip](https://github.com/xcp-ng/xenadmin/files/1888200/XCP-ng_Console_7.4.0.1_x64.zip)

**Comment by olivierlambert** [comment]
Yes that's a good choice to do as you said @borzel

**Comment by gangsterrapper22** [comment]
I have uploaded an update MSI Installer with the XCP-ng Center which @borzel has uploaded. You can download it at my Github Page on https://github.com/gangsterrapper22/XCP-ng_Installer/releases/tag/0.2
The Installer is not perfect yet, but I think it does what it should do. Please check, if everything works for you.

**Comment by borzel** [comment]
@gangsterrapper22 Payload for the installer: [XCP-ng Console 7.4.0.3-beta.zip](https://github.com/xcp-ng/xenadmin/files/1900800/XCP-ng.Console.7.4.0.3-beta.zip)

(Maybe) Resolved:
- https://github.com/xcp-ng/xenadmin/issues/18 Tidy up Branding/Trademarks/License
- Fill AssemblyFileVersion - Idea from https://github.com/xcp-ng/xenadmin/issues/17 Show Version in Title

@olivierlambert @gangsterrapper22
I would say, if this release passes the "legal check", we release as next version 4.7.1 for embeding in XCP-ng 4.7.1. I tested @gangsterrapper22's msi-installer and it works just fine 👍

**Comment by borzel** [comment]
@gangsterrapper22 you referenced the wrong branch in https://github.com/xcp-ng/xenadmin/releases/tag/v7.4.0.2-beta-MSI ... it should be https://github.com/xcp-ng/xenadmin/tree/release-7.4.0.2 instead of master. Good luck for the next time ;-)

**Comment by borzel** [comment]
Yes, that's super :-) I added some dots and spaces. Like the idea with the complete release notes.

**Comment by borzel** [comment]
tried to install 4.7.0.3 over 4.7.0.2

![grafik](https://user-images.githubusercontent.com/5782951/38757803-9f41fb68-3f6e-11e8-8583-8de082ea4b56.png)

> There is allready an version of this product installed

**Comment by gangsterrapper22** [comment]
You have to uninstall the current version first. I didn't implement the Update yet, if you want to install a newer version.

**Comment by borzel** [comment]
Works now! 👍

**Comment by borzel** [comment]
@gangsterrapper22 I added a release branch for 7.4.1 https://github.com/xcp-ng/xenadmin/tree/release-7.4.1 so you can put/merge your installer into it

**Comment by borzel** [comment]
klicked the wrong button... reopened it...

**Comment by gangsterrapper22** [comment]
I have compiled the latest Version of 7.4.1 but in the Console it still shows 7.4.0 in the About Menu. You have also to correct the Versions in the AssemblyVersion.cs Files because after running the Branding Command they have the Version 7.4.0. and the Dot has to be removed, otherwise it won't compile. Could you please fix that, then I will update the Installer. Thanks.

**Comment by borzel** [comment]
ok, I check that

**Comment by borzel** [comment]
@gangsterrapper22 I created a draft release, there you can get the binaries and add your msi file. When you are ready, we or @olivierlambert have to click the release button :-)

I would release both, the binaries and the msi file, so everyone can choose.

**Comment by gangsterrapper22** [comment]
I have upadated the Installer and renamed everything to XCP-ng Center. Update from the previous installed Version works without any Problem. I have also created a draft release first. If the Installer is OK, I think we can release it.

**Comment by borzel** [comment]
why not putting all into one release? Binary and MSI.

**Comment by borzel** [comment]
Your filename is wrong ;-)

**Comment by borzel** [comment]
License should be BSD2-Clause, not lorem ipsum

**Comment by gangsterrapper22** [comment]
I will fix this tomorrow then.

**Comment by borzel** [comment]
Installer works!

**Comment by gangsterrapper22** [comment]
The Installer works, but I have found out, that you can install it several times and it displays also several times then in the Remove Programs. :-)

**Comment by borzel** [comment]
MSI is really hard... ;-)

**Comment by borzel** [comment]
In my win10, i can repair it (if I execute the installer again). so the GUID's are good in my opinion.

**Comment by gangsterrapper22** [comment]
I added now the BSD2- License to the Installer. The Problem is, that the most Tools to create a proper MSI are costing.

**Comment by borzel** [comment]
Just released https://github.com/xcp-ng/xenadmin/releases/tag/v7.4.1 so people can use it while we are waiting for the installer.

@gangsterrapper22 do you need help?

**Comment by gangsterrapper22** [comment]
I will build the MSI Installer later, because the Host on which the VM runs with which I build the MSI Installer has some problems.

**Comment by borzel** [comment]
ok

**Comment by borzel** [comment]
Looks all fine, i also tested the installer, works!

**Comment by gangsterrapper22** [comment]
OK, I have released it now.

**Comment by borzel** [comment]
should we/you close this issue?

**Comment by gangsterrapper22** [comment]
I will close the issue now, but can you tell me then when you release an new Version, so that I can update the Installer then?
