### ISSUE TITLE
MSI installer to ship with XCP-ng 7.5

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xenadmin#73]
Hi, I'm working on the release of XCP-ng 7.5 and we would like to include an appropriate installer for the windows  client as an MSI installer, as in previous releases.

Thanks!

**Comment by stormi** [comment]
Thanks. Yes, please, if you can provide one in the next few days that will be great.

**Comment by borzel** [comment]
@stormi Here is your payload: https://builds.schulzalex.de/xcp-ng/7.5/XCP-ng-Center-7.5.0.msi

**Comment by stormi** [comment]
Thanks @borzel!
