### ISSUE TITLE
xcp-ng centre opens citrix website page

### ISSUE THREAD

**Issue by aimdev** [xcp-ng/xenadmin#87]
**Describe the bug**
Opens browser on the Citrix Website

**To Reproduce**
Clicking the
'Download an XCP-ng License Server virtual appliance'
Opens a web page on the Citrix Site.

**Expected behavior**
Open a browser page on the xcp-ng site,
or remove option.

**Screenshots / Logfiles**
If applicable, add screenshots / logfiles to help explain your problem.

**Hard-/Software involved:**
 - Hardware: [e.g. Dell M620]
 - Host XCP-ng Version: [e.g. 7.4.1]
 - Client XCP-ng Center Version: [e.g. 7.4.2-RC2]
 - Desktop OS: [e.g. Windows 10 1803]

**Additional context**

**Comment by olivierlambert** [comment]
@borzel it's up to you to decide what do you want to do. If you feel that's relevant to have something like "pro support" linking to xcp-ng.com website, that's your call. If you don't want to, no problem at all.

**Comment by borzel** [comment]
Version 7.5.0.8: If I click at these links I get only a messagebox.

![grafik](https://user-images.githubusercontent.com/5782951/43488166-1437c574-9519-11e8-9af6-5464c88e603a.png)

**Comment by borzel** [comment]
@olivierlambert follow up: https://github.com/xcp-ng/xenadmin/issues/88

**Comment by aimdev** [comment]
Hi
I am on 7.4.1, btw 'Buy Licenses' has the same issue. Going to 7.5 later. If its fixed then great.
