### ISSUE TITLE
7.5.0.8 binary put in Avira Quarantine

### ISSUE THREAD

**Issue by loopway** [xcp-ng/xenadmin#91]
**Describe the bug**
I've downloaded the 7.5.0.8 binary release (
https://github.com/xcp-ng/xenadmin/releases/download/v7.5.0/XCP-ng-Center-7.5.0.8.ms) and my Avira Free Antivirus (v15.0.37.326, Virus Definition File 8.15.3.150, Engine Version 8.3.52.38) on Windows 10 Pro (1803) put the file C:\Program Files (x86)\XCP-ng Center\XCP-ng Center.exe in Quarantine because of suspicion of the TR/Crypt.XPACK.Gen2 Trojaner.

**To Reproduce**
1. Download and Install xcp-ng xenadmin
2. Find exe in Quarantine

**Comment by borzel** [comment]
No need to worry:

https://www.virustotal.com/#/url/5626adf83c435971019945dbdf26aa5396524ce26fc7a28a3510e9e9e488755d/detection

Please update your Avira. If this does not help, report to Avira.

**Comment by borzel** [comment]
It's clearly a bug of Avira!

https://www.virustotal.com/#/file/9fe0e8f89963548f27bc997bf36aed4c340e0e35b902384a1e86d24bb283ea62/detection

**Comment by loopway** [comment]
thanks for double-checking!
