### ISSUE TITLE
Show Graph data with MBit instead of Mbps

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xenadmin#92]
~~make it configurable~~

**Comment by Kalloritis** [comment]
Has there been any progression on this?

I for one would like to see Mbps for network throughput, but disk throughput be MBps- I also agree though that these should be configurable to the user.

**Comment by borzel** [comment]
We do it when we have spare time. Or someone else has time - hey it's open source!

**Comment by Gatak** [comment]
I was always confused as to what the graphs showed. Ideally, I think, graphs should use IECunits.
kilyobytes, megabytes, gigabytes becomes KiB, MiB, GiB, and so on. The same for speeds; MiB/s, GiB/s...

 https://en.wikipedia.org/wiki/Mebibyte

**Comment by schulz-alexander** [comment]
Here the calculation of the "MBps" is performed, if `isRate` is true
https://github.com/xcp-ng/xenadmin/blob/834a5beda064189e18f07bdf7de15964dfd03a83/XenModel/Utils/Util.cs#L173-L204

**Comment by schulz-alexander** [comment]
First little Test: MBps -> MBit/s

![grafik](https://user-images.githubusercontent.com/5782951/58133751-f7d35580-7c24-11e9-8977-b725cba012e6.png)

Code (modified MBps and GBps):
```
private static string ByteSizeString(double bytes, int decPlaces, bool isRate, out string unit, string format = null)
        {
            if (bytes >= BINARY_TERA)
            {
                unit = isRate ? Messages.VAL_TERRATE : Messages.VAL_TERB;
                var result = Math.Round(bytes / BINARY_TERA, decPlaces);
                return string.IsNullOrEmpty(format) ? result.ToString() : result.ToString(format);
            }
            if (bytes >= BINARY_GIGA)
            {
                unit = isRate ? "GBit/s" /*Messages.VAL_GIGRATE*/ : Messages.VAL_GIGB;
                var result = isRate ? Math.Round((bytes*8) / (BINARY_GIGA), decPlaces) : Math.Round(bytes / BINARY_GIGA, decPlaces);
                return string.IsNullOrEmpty(format) ? result.ToString() : result.ToString(format);
            }

            if (bytes >= BINARY_MEGA)
            {
                unit = isRate ? "MBit/s" /*Messages.VAL_MEGRATE*/ : Messages.VAL_MEGB;
                var result = isRate ? Math.Round((bytes*8) / (BINARY_MEGA), decPlaces) : Math.Round(bytes / BINARY_MEGA, decPlaces);
                return string.IsNullOrEmpty(format) ? result.ToString() : result.ToString(format);
            }

            if (bytes >= BINARY_KILO)
            {
                unit = isRate ? Messages.VAL_KILRATE : Messages.VAL_KILB;
                var result = Math.Round(bytes / BINARY_KILO, decPlaces);
                return string.IsNullOrEmpty(format) ? result.ToString() : result.ToString(format);
            }

            unit = isRate ? Messages.VAL_RATE : Messages.VAL_BYTE;
            return bytes.ToString();
        }
```

**Comment by schulz-alexander** [comment]
Here my idea:

* use `Bit/s, KBit/s, MBit/s, GBit/s, TBit/s` for Network
* use `Byte/s, KByte/s, MByte/s, GByte/s, TByte/s` instead of Bps, kBps, MBps, GBps, TBps

![grafik](https://user-images.githubusercontent.com/5782951/58372946-e2f90980-7f25-11e9-9fda-a4004c14f14f.png)

**Comment by ghost** [comment]
I would suggest be more clear and use KiB and Kibit and equivalent. There's a difference between base 10 and binary numbers.

https://sv.m.wikipedia.org/wiki/Mall:Multipler_av_byte
https://en.m.wikipedia.org/wiki/Template:Bit_and_byte_prefixes

Kilobyte, kB = 10^3 = 1000 bytes
Kibibyte, KiB = 2^10 = 1024 bytes

KiB is what most people mean when talking KB, but there are exceptions. Storage manufacturers usually use the SI units, which is 10^x.

**Comment by schulz-alexander** [comment]
I'm everytime confused with that KiBit ... it's about digital data, so why should someone think in 1000 for K?

I think KBit and KByte is clear enough in our context.

**Comment by sza-mot** [comment]
I like the idea.
But the correct name for bit is **_bit_**, not Bit.
Well, the correct name for byte is byte, not Byte, but Byte is better "visible" and matches the unit symbol, so I'm OK with Byte.

[https://en.wikipedia.org/wiki/Bit](https://en.wikipedia.org/wiki/Bit):

> The symbol for the binary digit is either simply **bit** per recommendation by the IEC 80000-13:2008 standard, or the **lowercase character b**, as recommended by the IEEE 1541-2002 and IEEE Std 260.1-2004 standards.

[https://en.wikipedia.org/wiki/Byte#Unit_symbol](https://en.wikipedia.org/wiki/Byte#Unit_symbol):

> The unit symbol for the byte is specified in IEC 80000-13, IEEE 1541 and the Metric Interchange Format[9] as the **upper-case character B**. In contrast, IEEE 1541 specifies the **lower case character b as the symbol for the bit**, but IEC 80000-13 and Metric-Interchange-Format specify the symbol as **bit**, providing disambiguation from B for byte. 

(bolding by me).

**Comment by schulz-alexander** [comment]
we will not work on that
