### ISSUE TITLE
Different colors/notification icons

### ISSUE THREAD

**Issue by fraggan** [xcp-ng/xenadmin#94]
Hi, I would like to have different colors/notification icons down at the "notification tab" in XCP-ng Center. Now it's a red circle with a number in it. That kinda feels like an error message to me. It would be nice to see green ones when there are informal and maybe yellow with warnings and red when something is wrong.

Edit: Today I got the yellow icon when one of my hosts used to much memory. But the notification down at the "Notifications" showed a red one. Not a major thing but I would prefer same color there as in the "message view". Just to be able to see fast/easy if there is something I need to check now or if it can wait.

**Comment by borzel** [comment]
can you please first open a bug here: https://github.com/xenserver/xenadmin/issues

**Comment by borzel** [comment]
https://github.com/xenserver/xenadmin/issues/2192
