### ISSUE TITLE
Snapshot Schedules, run history incorrect time.

### ISSUE THREAD

**Issue by dnwahs** [xcp-ng/xenadmin#96]
**Describe the bug**
When viewing snapshot schedules and viewing the run history the time under the run history, which is taken from the notifications area is showing the incorrect time, is incorrect. 
The logs in the notification area have the correct time. 

**To Reproduce**
1. Go to 'Pool'
2. Click on '...'
3. Scroll down to and click on 'VM Snapshot Schedules'
4. New window will open
5. In new window click on a previously defined schedule that has been run at least once. 
6. Click on "Show Run History"
4. Assuming you didn't clear your logs under events at this point you should see previous snapshots that have been run by this policy. The time referenced here is incorrect.

**Comment by borzel** [comment]
fixed with: https://github.com/xcp-ng/xenadmin/commit/64999c5e7a78b159ee0aa8ce49fd9f8561837aa6
