### ISSUE TITLE
Pool -> Export Resource Data  Fails to create excel file

### ISSUE THREAD

**Issue by patelnet** [xcp-ng/xenadmin#99]
**Describe the bug**
When trying to export Resource Data of any pool, the job fails saying "Exporting pool resouce list failed from 'POOLNAME' Export Failed.  When selecting .xls as the export type.

**To Reproduce**
1. Select a pool 
2. Click on Pool from the top menu bar
3. Scroll down to Export Resource Date
4. Select a place to save the file.
5. Failure reported under notification.

**Expected behavior**
An .xls file similar to .csv file that is able to generate correctly.

**Hard-/Software involved:**
 - Hardware: HP DL165 G7
 - Host XCP-ng Version: 7.5.0.8
 - Client XCP-ng Center Version: [e.g. 7.4.2-RC2]
 - Desktop OS: [e.g. Windows 10 1803]

**Additional context**

**Comment by gangsterrapper22** [comment]
I tested the same on a single Host and there I can't reproduce it. I get an normal .xls File which can also be opened wihtout any error. I used the XCP-ng Center Version 7.5 build 7.5.0.8. Can you tell me which XCP-ng Center Version do you use, when you tried the export?

**Comment by borzel** [comment]
@patelnet do you have any response for us?

**Comment by borzel** [comment]
@patelnet please reopen the issue if you need to :-)

**Comment by cocoon** [comment]
I found out the problem and it exists with 7.6.0 RC3 setup.
If the following file is missing (seems not to be installed with the installer):

**C:\Program Files (x86)\XCP-ng Center\resource_report.rdlc**

**Comment by borzel** [comment]
Now I know what this weird file was for. Good to know.

The program path issue should be an extra ticket.

**Comment by borzel** [comment]
without branding it works now in 7.6... hmm...

**Comment by borzel** [comment]
now it works everytime ... weird ...

**Comment by borzel** [comment]
ahhhh.... the icon on the desktop (which the installer creates) does not contain a work path... now it really works :-)

**Comment by cocoon** [comment]
Great! Will try it today.

**Comment by cocoon** [comment]
Confirmed, report is working with the new version. 👍
